import { useEffect } from 'react';
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { Activity, BarChart3, CreditCard, Gift, GraduationCap, LayoutDashboard, LogOut, Package, ScanLine, ShoppingBag, Users, UtensilsCrossed } from 'lucide-react';
import { useAuthStore } from '../../store/authStore';
import { useDataStore } from '../../store/dataStore';
import { canAccessStudent } from '../../lib/access';
import { Button } from '../components/ui/button';
import { Toaster } from '../components/ui/sonner';
import { QuickBiteLogo } from '../components/brand/QuickBiteLogo';

export function AdminLayoutFixed(){ const navigate=useNavigate();const location=useLocation();const {user,signOut}=useAuthStore();const {loadData,orders}=useDataStore();useEffect(()=>{void loadData();},[loadData]);if(!user)return null;const pending=orders.filter(o=>!o.admin_hidden&&o.status==='pending').length;const active=(p:string)=>location.pathname===p||location.pathname.startsWith(`${p}/`);const items=[['/admin', 'Dashboard', LayoutDashboard],['/admin/orders','Pedidos',ShoppingBag],['/admin/payments','Pagos',CreditCard],['/admin/inventory','Inventario',Package],['/admin/menu','Menú',UtensilsCrossed],['/admin/verification','Verificación',ScanLine],['/admin/users','Usuarios',Users],['/admin/loyalty','Puntos y premios',Gift],['/admin/automation','Automatización',Activity],['/admin/reports','Informes',BarChart3]] as const;return <div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 z-30 w-64 bg-blue-900 p-4 text-white shadow-xl"><div className="mb-6 flex items-center gap-3"><QuickBiteLogo className="h-10 w-10 rounded-xl" alt="QuickBite Admin"/><div><p className="font-black">QuickBite Admin</p><p className="text-xs text-blue-200">Panel de control</p></div></div><nav className="space-y-1">{items.map(([path,label,Icon])=><Link key={path} to={path} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold ${active(path)?'bg-white/15 text-white':'text-blue-100 hover:bg-white/10'}`}><Icon className="h-4 w-4"/><span className="flex-1">{label}</span>{path==='/admin/orders'&&pending>0&&<span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs text-blue-900">{pending}</span>}</Link>)}</nav><div className="absolute bottom-4 left-4 right-4 border-t border-white/10 pt-4">{canAccessStudent(user.role)&&<Link to="/menu" className="mb-2 flex items-center justify-center rounded-lg border border-white/20 px-3 py-2 text-xs font-bold text-blue-100"> <GraduationCap className="mr-2 h-4 w-4"/>Ver como estudiante</Link>}<Button onClick={async()=>{await signOut();navigate('/');}} variant="outline" className="w-full border-white/20 bg-transparent text-white"><LogOut className="mr-2 h-4 w-4"/>Cerrar sesión</Button></div></aside><main className="ml-64 min-h-screen p-6 lg:p-8"><Outlet/></main><Toaster position="top-center"/></div>; }
