import { useCallback, useEffect, useState } from 'react';
import { Clock3, Zap, TimerReset, RefreshCw } from 'lucide-react';
import { requireSupabaseClient } from '../../../lib/supabase';

type RecessItem={id:string;name:string;start_time:string;end_time:string;minutes_remaining?:number;starts_in_minutes?:number;scope_level:number};
type RecessStatus={date:string;timezone:string;is_active:boolean;active:RecessItem|null;next:RecessItem|null};
function timeLabel(v:string){return v.slice(0,5)}
export function StudentRecessStatus(){
 const [status,setStatus]=useState<RecessStatus|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(false);
 const load=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);try{const{data,error:rpcError}=await requireSupabaseClient().rpc('get_student_recess_status');if(rpcError)throw rpcError;setStatus(data as RecessStatus);setError(false);}catch{setError(true)}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer)},[load]);
 if(loading)return <div className="rounded-2xl border border-slate-800 bg-[#121A2F] p-4 text-sm text-slate-400">Cargando tu horario de recreo…</div>;
 if(error)return <div className="flex items-center justify-between gap-3 rounded-2xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-200"><span>No se pudo consultar tu recreo.</span><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="inline-flex items-center gap-2 rounded-xl border border-amber-500/30 px-3 py-2 text-xs font-black"><RefreshCw className={refreshing?'h-3.5 w-3.5 animate-spin':'h-3.5 w-3.5'}/>Actualizar</button></div>;
 const active=status?.active??null; const next=status?.next??null;
 return <section aria-label="Estado del recreo" className={`overflow-hidden rounded-3xl border p-5 shadow-lg ${active?'border-emerald-500/30 bg-emerald-500/10':'border-slate-800 bg-[#121A2F]'}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${active?'bg-emerald-500/15 text-emerald-400':'bg-slate-800 text-slate-400'}`}>{active?<Zap className="h-5 w-5"/>:<TimerReset className="h-5 w-5"/>}</div><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Modo recreo</p><h2 className="mt-1 text-xl font-black text-white">{active?'RECREO ACTIVO':'Recreo no activo'}</h2>{active?<p className="mt-1 text-sm text-emerald-200">{active.name} · {timeLabel(active.start_time)} – {timeLabel(active.end_time)} · {active.minutes_remaining??0} min restantes</p>:next?<p className="mt-1 text-sm text-slate-400">Próximo: <span className="font-bold text-white">{next.name}</span> · {timeLabel(next.start_time)} – {timeLabel(next.end_time)} · en {next.starts_in_minutes??0} min</p>:<p className="mt-1 text-sm text-slate-400">No tienes otro recreo configurado para hoy.</p>}</div></div><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-3.5 py-2 text-xs font-black text-slate-200 transition hover:bg-slate-700 disabled:opacity-50"><RefreshCw className={refreshing?'h-3.5 w-3.5 animate-spin':'h-3.5 w-3.5'}/>Actualizar</button></div><div className="mt-4 flex items-center gap-2 text-xs font-semibold text-slate-500"><Clock3 className="h-3.5 w-3.5"/>Horario calculado según tu sección, grado y curso</div></section>;
}