import { useCallback, useEffect, useState } from 'react';
import { BarChart3, Boxes, Clock3, Plus, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { requireSupabaseClient } from '../../../lib/supabase';

type Slot = { slot_id:string; slot_name:string; starts_at:string; ends_at:string; enabled:boolean; max_orders:number|null; orders_count:number; accepting_orders:boolean };
type Ranking = { product_id:string; name:string; units_sold:number; revenue:number; order_count:number };
type Inventory = { id:string; name:string; price:number; available_stock:number; reserved_stock:number; total_stock:number; available:boolean };
const money=(n:number)=>Number(n).toLocaleString('es-CO');

export function AdminOperations() {
 const [slots,setSlots]=useState<Slot[]>([]); const [rankings,setRankings]=useState<Ranking[]>([]); const [inventory,setInventory]=useState<Inventory[]>([]); const [loading,setLoading]=useState(true);
 const [form,setForm]=useState({name:'Receso',starts:'09:30',ends:'10:00',max:'30'}); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const c=requireSupabaseClient();const [s,r,i]=await Promise.all([c.rpc('get_order_window_status'),c.from('product_sales_rankings').select('*').order('units_sold',{ascending:false}).limit(20),c.from('product_inventory_status').select('*').order('reserved_stock',{ascending:false}).limit(50)]);if(s.error)throw s.error;if(r.error)throw r.error;if(i.error)throw i.error;setSlots((s.data??[]) as Slot[]);setRankings((r.data??[]) as Ranking[]);setInventory((i.data??[]) as Inventory[]);}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar operaciones.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const saveSlot=async()=>{setSaving(true);try{const c=requireSupabaseClient();const {error}=await c.rpc('admin_upsert_pickup_slot',{p_id:null,p_name:form.name,p_starts_at:form.starts,p_ends_at:form.ends,p_enabled:true,p_max_orders:form.max?Number(form.max):null});if(error)throw error;toast.success('Ventana de pedidos creada.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo guardar la ventana.')}finally{setSaving(false)}};
 const toggleSlot=async(s:Slot)=>{try{const {error}=await requireSupabaseClient().rpc('admin_upsert_pickup_slot',{p_id:s.slot_id,p_name:s.slot_name,p_starts_at:s.starts_at,p_ends_at:s.ends_at,p_enabled:!s.enabled,p_max_orders:s.max_orders});if(error)throw error;await load();}catch(e){toast.error(e instanceof Error?e.message:'No se pudo actualizar la ventana.')}};
 return <div className="space-y-7"><header className="rounded-[2rem] border border-blue-100 bg-gradient-to-br from-white to-blue-50 p-6 shadow-xl sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Operación avanzada</p><h1 className="mt-2 text-3xl font-black text-slate-950">Control operativo</h1><p className="mt-2 text-sm text-slate-600">Ventanas de pedido, capacidad, inventario reservado y ranking real de productos.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Actualizar</button></div></header>
 <section className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-blue-700"/><div><h2 className="text-xl font-black">Ventanas de pedidos</h2><p className="text-sm text-slate-500">Define cuándo se aceptan pedidos y el máximo de pedidos por ventana.</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-5"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nombre" className="rounded-xl border p-3 text-sm"/><input type="time" value={form.starts} onChange={e=>setForm({...form,starts:e.target.value})} className="rounded-xl border p-3 text-sm"/><input type="time" value={form.ends} onChange={e=>setForm({...form,ends:e.target.value})} className="rounded-xl border p-3 text-sm"/><input type="number" min="1" value={form.max} onChange={e=>setForm({...form,max:e.target.value})} placeholder="Máximo" className="rounded-xl border p-3 text-sm"/><button disabled={saving} onClick={()=>void saveSlot()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-sm font-black text-white"><Plus className="h-4 w-4"/>Crear</button></div><div className="mt-4 space-y-2">{slots.map(s=><div key={s.slot_id} className="flex flex-col gap-2 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{s.slot_name} · {s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)}</p><p className="text-xs text-slate-500">{s.orders_count} pedidos hoy · límite {s.max_orders??'sin límite'} · {s.accepting_orders?'Aceptando ahora':'Cerrada ahora'}</p></div><button onClick={()=>void toggleSlot(s)} className={`rounded-xl px-3 py-2 text-xs font-black ${s.enabled?'bg-emerald-100 text-emerald-800':'bg-slate-200 text-slate-600'}`}>{s.enabled?'Activa':'Desactivada'}</button></div>)}{!loading&&slots.length===0&&<p className="rounded-2xl border border-dashed p-5 text-sm text-slate-500">No hay ventanas configuradas.</p>}</div></section>
 <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Boxes className="h-5 w-5 text-emerald-700"/><div><h2 className="text-xl font-black">Inventario reservado</h2><p className="text-sm text-slate-500">Disponible, reservado por pedidos activos y total comprometido.</p></div></div><div className="mt-4 space-y-2">{inventory.slice(0,12).map(i=><div key={i.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span className="font-bold">{i.name}</span><span>Disp. <b>{i.available_stock}</b> · Res. <b>{i.reserved_stock}</b> · Total <b>{i.total_stock}</b></span></div>)}</div></div><div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><BarChart3 className="h-5 w-5 text-violet-700"/><div><h2 className="text-xl font-black">Ranking de productos</h2><p className="text-sm text-slate-500">Ventas confirmadas y entregadas.</p></div></div><div className="mt-4 space-y-2">{rankings.slice(0,12).map((r,idx)=><div key={r.product_id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span><b>#{idx+1}</b> {r.name}</span><span className="font-bold">{r.units_sold} uds · ${money(Number(r.revenue))}</span></div>)}</div></div></section>
 </div>;
}
