import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarDays, FileSpreadsheet, RefreshCw, ShoppingBag, TrendingUp } from 'lucide-react';
import * as XLSX from '@redoper1/xlsx-js-style';
import { toast } from 'sonner';
import { requireSupabaseClient } from '../../../lib/supabase';
import { buildActiveSalesWorkbook, type SalesRedemptionExport } from '../../../services/orderExportService';
import type { Order } from '../../../lib/supabase';
import { Button } from '../../components/ui/button';
import { Card } from '../../components/ui/card';

type Mode = 'daily' | 'weekly' | 'monthly';
const dayKey = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function parseDate(v: string) { const [y,m,d]=v.split('-').map(Number); return new Date(y,m-1,d,12); }
function businessDays(end: Date, count: number) { const result: Date[]=[]; const cursor=new Date(end); cursor.setHours(12,0,0,0); while(result.length<count){ const w=cursor.getDay(); if(w!==0&&w!==6) result.unshift(new Date(cursor)); cursor.setDate(cursor.getDate()-1);} return result; }
function range(mode: Mode, selected: Date){ const days=businessDays(selected, mode==='daily'?1:mode==='weekly'?5:20); return {start:new Date(days[0].getFullYear(),days[0].getMonth(),days[0].getDate()), end:new Date(days.at(-1)!.getFullYear(),days.at(-1)!.getMonth(),days.at(-1)!.getDate(),23,59,59), days}; }
const money=(n:number)=>n.toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});

export function AdminReportsFixed(){
 const [mode,setMode]=useState<Mode>('daily'); const [selectedDate,setSelectedDate]=useState(dayKey(new Date())); const [orders,setOrders]=useState<Order[]>([]); const [redemptions,setRedemptions]=useState<SalesRedemptionExport[]>([]); const [loading,setLoading]=useState(true); const selected=useMemo(()=>parseDate(selectedDate),[selectedDate]); const r=useMemo(()=>range(mode,selected),[mode,selected]);
 const load=useCallback(async()=>{ setLoading(true); try{ const c=requireSupabaseClient(); const [o,red]=await Promise.all([c.from('orders').select('*,order_items(*,product:products(*,category:categories(*))),user:profiles(*)').gte('created_at',r.start.toISOString()).lte('created_at',r.end.toISOString()).order('created_at'),c.from('loyalty_redemptions').select('id,redemption_code,points_spent,status,created_at,admin_hidden,reward:loyalty_rewards(title,product:products(name)),user:profiles!loyalty_redemptions_user_id_fkey(full_name,email)').gte('created_at',r.start.toISOString()).lte('created_at',r.end.toISOString()).order('created_at')]); if(o.error)throw o.error;if(red.error)throw red.error;setOrders((o.data??[]) as unknown as Order[]);setRedemptions((red.data??[]) as unknown as SalesRedemptionExport[]);}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar el informe.');setOrders([]);setRedemptions([]);}finally{setLoading(false);} },[r]);
 useEffect(()=>{void load();},[load]);
 const confirmed=useMemo(()=>orders.filter(o=>o.payment_status==='confirmed'&&o.status!=='cancelled'),[orders]); const total=confirmed.reduce((s,o)=>s+Number(o.total),0); const units=confirmed.reduce((s,o)=>s+(o.order_items??[]).reduce((x,i)=>x+i.quantity,0),0); const avg=confirmed.length?total/confirmed.length:0;
 const perDay=useMemo(()=>r.days.map(d=>{const k=dayKey(d);const os=orders.filter(o=>dayKey(new Date(o.created_at))===k);const cs=os.filter(o=>o.payment_status==='confirmed'&&o.status!=='cancelled');return {k, label:d.toLocaleDateString('es-CO',{weekday:'short',day:'2-digit',month:'short'}), orders:os.length,sales:cs.reduce((s,o)=>s+Number(o.total),0),units:cs.reduce((s,o)=>s+(o.order_items??[]).reduce((x,i)=>x+i.quantity,0),0)};}),[orders,r.days]);
 const weekly=useMemo(()=>Array.from({length:4},(_,i)=>{const s=perDay.slice(i*5,i*5+5);return {label:`Semana ${i+1}`,orders:s.reduce((x,d)=>x+d.orders,0),sales:s.reduce((x,d)=>x+d.sales,0),units:s.reduce((x,d)=>x+d.units,0)};}),[perDay]);
 const download=()=>{ if(!orders.length){toast.info('No hay datos para exportar.');return;} try{const wb=buildActiveSalesWorkbook(orders,redemptions,{includeHidden:true});XLSX.writeFile(wb,`QuickBite-informe-${mode}-${selectedDate}.xlsx`,{compression:true}); const fn=requireSupabaseClient().rpc('clear_exported_redemptions'); void fn.then(({error})=>{if(error)toast.error('Excel descargado, pero no se pudieron limpiar los canjes históricos.');else{setRedemptions([]);toast.success('Excel descargado y canjes históricos limpiados.');}});}catch(e){toast.error(e instanceof Error?e.message:'No se pudo generar el Excel.');} };
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-3"><BarChart3 className="h-8 w-8 text-blue-700"/><h1 className="text-4xl font-bold text-blue-900">Informes</h1></div><p className="mt-2 text-slate-600">Histórico real de Diario, Semanal y Mensual con exportación Excel.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button><Button onClick={download} disabled={loading||!orders.length} className="bg-green-600 text-white"><FileSpreadsheet className="mr-2 h-4 w-4"/>Descargar Excel</Button></div></div>
 <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex rounded-xl bg-slate-100 p-1">{([['daily','Diario'],['weekly','Semanal'],['monthly','Mensual']] as const).map(([v,l])=><button key={v} type="button" onClick={()=>setMode(v)} className={`rounded-lg px-5 py-2 font-bold ${mode===v?'bg-blue-700 text-white':'text-slate-600'}`}>{l}</button>)}</div><label className="flex items-center gap-2 text-sm font-semibold"><CalendarDays className="h-4 w-4"/>Fecha<input className="rounded-lg border px-3 py-2" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></label></div><p className="mt-2 text-xs text-slate-500">{mode==='daily'?'1 día operativo':mode==='weekly'?'5 días operativos (lunes a viernes)':'4 semanas × 5 días operativos'}</p></Card>
 <div className="grid gap-4 md:grid-cols-4"><Kpi icon={TrendingUp} t="Ventas" v={money(total)}/><Kpi icon={ShoppingBag} t="Pedidos" v={String(orders.length)}/><Kpi icon={FileSpreadsheet} t="Unidades" v={String(units)}/><Kpi icon={BarChart3} t="Ticket promedio" v={money(avg)}/></div>
 <Card className="p-5"><h2 className="text-xl font-bold text-slate-900">{mode==='monthly'?'Resumen por semanas':'Desglose diario'}</h2>{mode==='monthly'?<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{weekly.map(w=><div key={w.label} className="rounded-xl bg-slate-50 p-4"><b>{w.label}</b><p className="mt-2 text-xl font-black text-blue-900">{money(w.sales)}</p><p className="text-xs text-slate-500">{w.orders} pedidos · {w.units} unidades</p></div>)}</div>:<div className="mt-4 space-y-3">{perDay.map(d=><div key={d.k} className="flex items-center gap-3"><span className="w-28 text-sm font-semibold capitalize">{d.label}</span><div className="h-3 flex-1 rounded bg-slate-100"><div className="h-3 rounded bg-blue-600" style={{width:`${Math.max(d.sales?4:0,Math.min(100,(d.sales/Math.max(...perDay.map(x=>x.sales),1))*100))}%`}}/></div><span className="w-28 text-right text-sm font-bold">{money(d.sales)}</span></div>)}</div>}</Card>
 <Card className="p-5"><h2 className="mb-3 text-xl font-bold text-slate-900">Canjes históricos</h2>{redemptions.length?<div className="space-y-2">{redemptions.map(x=><div key={x.id} className="flex justify-between rounded-lg bg-slate-50 p-3"><span>{x.redemption_code??x.id.slice(0,8)} · {x.user?.full_name??'Estudiante'} · {x.reward?.title??'Recompensa'}</span><b>{x.points_spent} puntos</b></div>)}</div>:<p className="text-sm text-slate-500">No hay canjes históricos en este período.</p>}</Card>
 </div>;
}
function Kpi({icon:Icon,t,v}:{icon:typeof TrendingUp;t:string;v:string}){return <Card className="p-5"><div className="mb-2 flex justify-between"><span className="text-sm text-slate-500">{t}</span><Icon className="h-5 w-5 text-blue-600"/></div><p className="text-2xl font-black">{v}</p></Card>;}
