import { useEffect, useState } from 'react';
import { Leaf, Save } from 'lucide-react';
import { toast } from 'sonner';
import { useDataStore } from '../../../store/dataStore';
import { requireSupabaseClient } from '../../../lib/supabase';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Textarea } from '../../components/ui/textarea';

interface Nutrition { product_id: string; calories: number | null; protein_g: number | null; carbohydrates_g: number | null; fat_g: number | null; fiber_g: number | null; ingredients: string | null; allergens: string | null; vegetarian: boolean; healthy_choice: boolean; }
const empty = (id: string): Nutrition => ({ product_id:id, calories:null, protein_g:null, carbohydrates_g:null, fat_g:null, fiber_g:null, ingredients:'', allergens:'', vegetarian:false, healthy_choice:false });
export function AdminNutrition() {
  const { products } = useDataStore(); const [rows,setRows]=useState<Record<string,Nutrition>>({}); const [saving,setSaving]=useState<string|null>(null);
  useEffect(()=>{ void (async()=>{ try { const {data,error}=await requireSupabaseClient().from('product_nutrition').select('*'); if(error) throw error; const next:Record<string,Nutrition>={}; (data??[]).forEach((row)=>{next[row.product_id]=row as Nutrition}); setRows(next); } catch(error){ toast.error(error instanceof Error?error.message:'No se pudo cargar la información nutricional.'); } })(); },[]);
  const update=(id:string, patch:Partial<Nutrition>)=>setRows((current)=>({...current,[id]:{...(current[id]??empty(id)),...patch}}));
  const save=async(id:string)=>{setSaving(id);try{const row=rows[id]??empty(id);const {error}=await requireSupabaseClient().from('product_nutrition').upsert({...row,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(error)throw error;toast.success('Información nutricional guardada.')}catch(error){toast.error(error instanceof Error?error.message:'No se pudo guardar.')}finally{setSaving(null)}};
  return <div className="space-y-6"><div><div className="flex items-center gap-3"><Leaf className="h-7 w-7 text-emerald-600"/><div><h1 className="text-3xl font-black">Información nutricional</h1><p className="text-sm text-slate-500">Completa los datos que verán los padres en Alimentación y bienestar.</p></div></div></div><div className="grid gap-5 lg:grid-cols-2">{products.map((product)=>{const row=rows[product.id]??empty(product.id);return <article key={product.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-black text-slate-900">{product.name}</h2><p className="text-xs text-slate-500">{product.description??'Sin descripción'}</p></div><div className="grid grid-cols-2 gap-3">{([['calories','Calorías (kcal)'],['protein_g','Proteína (g)'],['carbohydrates_g','Carbohidratos (g)'],['fat_g','Grasa (g)'],['fiber_g','Fibra (g)']] as const).map(([key,label])=><label key={key} className="space-y-1"><span className="text-xs font-bold text-slate-600">{label}</span><Input type="number" min="0" step="0.1" value={row[key]??''} onChange={(e)=>update(product.id,{[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<label className="col-span-2 space-y-1"><span className="text-xs font-bold text-slate-600">Ingredientes</span><Textarea value={row.ingredients??''} onChange={(e)=>update(product.id,{ingredients:e.target.value})} rows={2}/></label><label className="col-span-2 space-y-1"><span className="text-xs font-bold text-slate-600">Alérgenos</span><Input value={row.allergens??''} onChange={(e)=>update(product.id,{allergens:e.target.value})} placeholder="Ej. leche, trigo, huevo"/></label></div><div className="mt-4 flex flex-wrap gap-4 text-sm font-semibold"><label className="flex items-center gap-2"><input type="checkbox" checked={row.vegetarian} onChange={(e)=>update(product.id,{vegetarian:e.target.checked})}/>Vegetariano</label><label className="flex items-center gap-2"><input type="checkbox" checked={row.healthy_choice} onChange={(e)=>update(product.id,{healthy_choice:e.target.checked})}/>Opción saludable</label></div><Button type="button" onClick={()=>void save(product.id)} disabled={saving===product.id} className="mt-4 w-full bg-emerald-600 font-black text-white hover:bg-emerald-700"><Save className="mr-2 h-4 w-4"/>{saving===product.id?'Guardando…':'Guardar información'}</Button></article>})}</div></div>;
}
