import { useMemo, useState } from 'react';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { Download, Eye, EyeOff, ShoppingBag } from 'lucide-react';
import { toast } from 'sonner';
import { downloadAllSalesExcel, type SalesRedemptionExport } from '../../../services/orderExportService';
import { requireSupabaseClient } from '../../../lib/supabase';
import { getErrorMessage } from '../../../lib/errorMessage';
import type { Order } from '../../../lib/supabase';
import { useDataStore } from '../../../store/dataStore';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card } from '../../components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { AdminRedemptionsSection } from './AdminRedemptionsSection';

const statusLabels: Record<Order['status'], { label: string; className: string }> = { pending: { label: 'Pedido recibido', className: 'bg-blue-600 text-white' }, preparing: { label: 'En preparación', className: 'bg-amber-500 text-white' }, ready: { label: 'Listo para recoger', className: 'bg-green-600 text-white' }, delivered: { label: 'Entregado', className: 'bg-green-800 text-white' }, cancelled: { label: 'Rechazado', className: 'bg-red-600 text-white' } };
const paymentLabels: Record<Order['payment_status'], { label: string; className: string }> = { confirmed: { label: 'Confirmado', className: 'bg-green-100 text-green-800' }, pending: { label: 'Pendiente', className: 'bg-amber-100 text-amber-800' }, rejected: { label: 'Rechazado', className: 'bg-red-100 text-red-800' } };
function getOrderErrorMessage(error: unknown) { const message = getErrorMessage(error, 'No se pudo completar la operación con Supabase'); if (message.includes('admin_hidden') || message.includes('column')) return 'Falta aplicar la migración admin_hidden en Supabase. Ejecuta la nueva migración y vuelve a intentarlo.'; if (/not_authorized|row-level security|permission denied/i.test(message)) return 'Tu sesión no tiene permisos de administrador para actualizar pedidos.'; return message; }
function getStatusBadge(status: Order['status']) { const c = statusLabels[status] ?? statusLabels.pending; return <Badge className={c.className}>{c.label}</Badge>; }
function getPaymentBadge(status: Order['payment_status']) { const c = paymentLabels[status] ?? paymentLabels.pending; return <Badge className={c.className}>Pago: {c.label}</Badge>; }
function getItemsCount(order: Order) { return order.order_items?.reduce((sum, item) => sum + item.quantity, 0) ?? 0; }

export function AdminOrders() {
  const { orders, updateOrder, resetOrdersForNewPeriod } = useDataStore();
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null); const [filterStatus, setFilterStatus] = useState('all'); const [showHidden, setShowHidden] = useState(false); const [updatingOrderId, setUpdatingOrderId] = useState<string | null>(null); const [closingPeriod, setClosingPeriod] = useState(false); const [showExportConfirm, setShowExportConfirm] = useState(false);
  const hiddenCount = useMemo(() => orders.filter((o) => o.admin_hidden).length, [orders]);
  const exportableOrders = useMemo(() => orders, [orders]);
  const exportTotal = useMemo(() => exportableOrders.filter((o) => o.payment_status === 'confirmed').reduce((s, o) => s + Number(o.total), 0), [exportableOrders]);
  const filteredOrders = useMemo(() => {
    let f = orders
      .filter((o) => !o.admin_hidden)
      .filter((o) => o.payment_status === 'confirmed' || o.payment_status === 'rejected')
      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    if (showHidden) {
      f = orders.filter((o) => o.admin_hidden && (o.payment_status === 'confirmed' || o.payment_status === 'rejected')).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    }
    if (filterStatus !== 'all') {
      f = f.filter((o) => filterStatus === 'cancelled' ? o.payment_status === 'rejected' : o.status === filterStatus);
    }
    return f;
  }, [orders, filterStatus, showHidden]);
  const handleStatusChange = async (id: string, status: Order['status']) => { if (updatingOrderId) return; setUpdatingOrderId(id); try { await updateOrder(id, { status }); toast.success('Estado del pedido actualizado'); if (selectedOrder?.id === id) setSelectedOrder({ ...selectedOrder, status }); } catch (e) { toast.error(getOrderErrorMessage(e)); } finally { setUpdatingOrderId(null); } };
  const handleHiddenChange = async (order: Order, hidden: boolean) => { try { await updateOrder(order.id, { admin_hidden: hidden }); toast.success(hidden ? 'Pedido archivado en Administración' : 'Pedido restaurado en Administración'); if (selectedOrder?.id === order.id) setSelectedOrder({ ...selectedOrder, admin_hidden: hidden }); } catch (e) { toast.error(getOrderErrorMessage(e)); } };
  const handleExcelDownload = async () => { if (closingPeriod) return; setClosingPeriod(true); let result; try { const { data, error } = await requireSupabaseClient().from('loyalty_redemptions').select('id,redemption_code,points_spent,status,created_at,admin_hidden,reward:loyalty_rewards(title,product:products(name)),user:profiles!loyalty_redemptions_user_id_fkey(full_name,email)').eq('admin_hidden', false).order('created_at', { ascending: true }); if (error) throw error; result = downloadAllSalesExcel(orders, (data ?? []) as unknown as SalesRedemptionExport[]); } catch (e) { toast.error(getOrderErrorMessage(e)); setClosingPeriod(false); return; } try { const resetCount = await resetOrdersForNewPeriod(); setSelectedOrder(null); setShowHidden(false); setShowExportConfirm(false); toast.success(`Se descargó el reporte completo con ${result.count} pedidos y se reiniciaron ${resetCount} pedidos, incluidos rechazados, archivados y canjes. El inventario no cambió.`); } catch (e) { toast.error(`El reporte se descargó, pero no se reiniciaron todos los pedidos. ${getOrderErrorMessage(e)}`); } finally { setClosingPeriod(false); } };
  return <div>
    <div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><h1 className="mb-2 text-4xl font-bold text-green-800">Gestión de pedidos</h1><p className="text-lg text-gray-600">Solo los pedidos aceptados o rechazados aparecen aquí. Los pendientes se revisan en Pagos.</p></div><Button type="button" onClick={() => setShowExportConfirm(true)} disabled={closingPeriod || exportableOrders.length === 0} className="bg-green-700 text-white hover:bg-green-800"><Download className="h-4 w-4" />{closingPeriod ? 'Cerrando período...' : 'Exportar Excel y reiniciar período'}</Button></div>
    <AdminRedemptionsSection />
    <Card className="mb-6 border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center gap-4"><label className="font-medium text-gray-700">Filtrar por estado:</label><Select value={filterStatus} onValueChange={setFilterStatus}><SelectTrigger className="w-64"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos los pedidos</SelectItem><SelectItem value="preparing">En preparación</SelectItem><SelectItem value="ready">Listos</SelectItem><SelectItem value="delivered">Entregados</SelectItem><SelectItem value="cancelled">Rechazados</SelectItem></SelectContent></Select><Button type="button" variant="outline" onClick={() => setShowHidden((v) => !v)} className="border-green-600 text-green-700 hover:bg-green-50">{showHidden ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}{showHidden ? 'Ver pedidos activos' : `Ver pedidos archivados (${hiddenCount})`}</Button><div className="ml-auto text-sm text-gray-600">Total: <span className="font-bold text-green-800">{filteredOrders.length}</span> pedido(s)</div></div></Card>
    {filteredOrders.length === 0 ? <Card className="border border-slate-200 bg-white p-12 text-center shadow-sm"><ShoppingBag className="mx-auto mb-4 h-16 w-16 text-gray-300" /><p className="text-lg text-gray-500">No hay pedidos para mostrar</p></Card> : <div className="space-y-4">{filteredOrders.map((order) => {
      const rejected = order.payment_status === 'rejected';
      const delivered = order.status === 'delivered';
      const terminal = rejected || delivered;
      return <Card key={order.id} className="border border-slate-200 bg-white p-6 shadow-sm transition hover:shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-3"><h3 className="text-2xl font-bold text-green-700">{order.order_number}</h3>{getStatusBadge(order.status)}{getPaymentBadge(order.payment_status)}{order.admin_hidden && <Badge className="bg-slate-200 text-slate-700">Archivado</Badge>}</div><p className="mb-3 text-sm text-gray-600">{format(new Date(order.created_at), "d 'de' MMMM, yyyy - HH:mm", { locale: es })}</p><div className="flex items-center gap-2 text-sm text-gray-600"><span className="font-medium">Artículos:</span><span>{getItemsCount(order)} unidades</span></div></div><div className="text-right"><p className="mb-1 text-sm text-gray-600">Total</p><p className="mb-3 text-3xl font-bold text-green-800">${Number(order.total).toLocaleString()}</p><div className="flex flex-wrap justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setSelectedOrder(order)} className="border-green-600 text-green-700 hover:bg-green-50">Ver detalles</Button>{!terminal && <Button size="sm" variant="outline" onClick={() => void handleHiddenChange(order, !order.admin_hidden)} className="border-slate-500 text-slate-700 hover:bg-slate-50">{order.admin_hidden ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}{order.admin_hidden ? 'Restaurar' : 'Archivar'}</Button>}</div></div></div>{!terminal && order.payment_status === 'confirmed' && order.status !== 'cancelled' && <div className="mt-4 border-t border-gray-200 pt-4"><div className="flex flex-wrap items-center gap-3"><span className="text-sm font-medium text-gray-700">Cambiar estado:</span>{(['preparing','ready','delivered'] as const).filter((s) => s !== order.status).map((s) => <Button key={s} size="sm" onClick={() => void handleStatusChange(order.id, s)} disabled={updatingOrderId === order.id} className={s === 'preparing' ? 'bg-amber-500 text-white hover:bg-amber-600' : 'bg-green-600 text-white hover:bg-green-700'}>{statusLabels[s].label}</Button>)}</div></div>}{terminal && <div className={`mt-4 rounded-2xl p-3 text-sm font-semibold ${rejected ? 'bg-red-50 text-red-800' : 'bg-green-50 text-green-800'}`}>{rejected ? 'Pedido rechazado. No se puede modificar.' : 'Pedido entregado. Estado final, sin acciones adicionales.'}</div>}</Card>;
    })}</div>}
    <Dialog open={showExportConfirm} onOpenChange={setShowExportConfirm}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Exportar ventas y reiniciar</DialogTitle></DialogHeader><div className="space-y-4"><p className="font-semibold text-slate-900">¿Deseas exportar todo el período a Excel y reiniciar la gestión de pedidos?</p><div className="rounded-2xl bg-green-50 p-4 text-sm text-slate-700"><p><strong>{exportableOrders.length}</strong> pedido(s) serán exportados, incluidos rechazados y archivados.</p><p className="mt-1"><strong>${exportTotal.toLocaleString('es-CO')}</strong> es el total confirmado del período.</p></div><p className="text-sm text-slate-600">Después del reinicio, todos los pedidos desaparecerán de la operación, pero quedarán registrados en el archivo descargado.</p><p className="text-sm font-medium text-amber-700">No se modificará nada si cancelas o si el archivo no puede generarse correctamente.</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowExportConfirm(false)} disabled={closingPeriod}>Cancelar</Button><Button type="button" onClick={() => void handleExcelDownload()} disabled={closingPeriod} className="bg-green-700 text-white hover:bg-green-800">{closingPeriod ? 'Exportando...' : 'Confirmar exportación'}</Button></div></div></DialogContent></Dialog>
    <Dialog open={!!selectedOrder} onOpenChange={() => setSelectedOrder(null)}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle className="text-2xl">Detalles del pedido</DialogTitle></DialogHeader>{selectedOrder && <div className="space-y-6"><div className="grid grid-cols-2 gap-4"><div><p className="text-sm text-gray-600">Número de orden</p><p className="text-xl font-bold text-green-700">{selectedOrder.order_number}</p></div><div><p className="text-sm text-gray-600">Total</p><p className="text-xl font-bold text-green-800">${Number(selectedOrder.total).toLocaleString()}</p></div><div><p className="text-sm text-gray-600">Estado</p>{getStatusBadge(selectedOrder.status)}</div><div><p className="text-sm text-gray-600">Método de pago</p><p className="font-medium capitalize">{selectedOrder.payment_method === 'cash' ? 'Efectivo' : selectedOrder.payment_method}</p></div></div><div><h3 className="mb-3 text-lg font-bold text-green-800">Artículos del pedido</h3>{selectedOrder.order_items?.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg bg-gray-50 p-3"><div><p className="font-medium">{item.product?.name}</p><p className="text-sm text-gray-600">{item.quantity} × ${Number(item.price).toLocaleString()}</p></div><span className="font-bold text-green-800">${Number(item.price * item.quantity).toLocaleString()}</span></div>)}</div>{selectedOrder.notes && <div className="rounded-2xl bg-green-50 p-4"><p className="font-bold text-green-800">Comentario del estudiante</p><p className="mt-1 text-sm text-slate-700">{selectedOrder.notes}</p></div>}</div>}</DialogContent></Dialog>
  </div>;
}
