import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarDays, FileSpreadsheet, RefreshCw, ShoppingBag, TrendingUp } from 'lucide-react';
import { toast } from 'sonner';
import { requireSupabaseClient, type Order } from '../../../lib/supabase';
import { buildActiveSalesWorkbook, type SalesRedemptionExport } from '../../../services/orderExportService';
import * as XLSX from '@redoper1/xlsx-js-style';
import { Button } from '../../components/ui/button';

type ReportMode = 'daily' | 'weekly' | 'monthly';
const salesHeaders = ['N.º pedido', 'Fecha de compra', 'Hora de compra', 'Cliente', 'Correo', 'Documento', 'Estado pedido', 'Estado pago', 'Método de pago', 'Código recogida', 'Referencia de pago', 'Total pedido', 'Productos', 'Unidades', 'Tiempo estimado (min)'];
const detailHeaders = ['N.º pedido', 'Fecha de compra', 'Hora de compra', 'Producto', 'Categoría', 'Precio unitario', 'Cantidad', 'Subtotal', 'Stock actual', 'Cliente'];
const redemptionHeaders = ['Código de canje', 'Fecha de canje', 'Estudiante', 'Correo', 'Recompensa', 'Producto', 'Puntos utilizados', 'Estado'];
const dateFormatter = new Intl.DateTimeFormat('es-CO', { timeZone: 'America/Bogota', year: 'numeric', month: '2-digit', day: '2-digit' });
const timeFormatter = new Intl.DateTimeFormat('es-CO', { timeZone: 'America/Bogota', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });
const currency = new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 });
function dateKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function parseInputDate(value: string) { const [year, month, day] = value.split('-').map(Number); return new Date(year, month - 1, day, 12, 0, 0); }
function operationalDaysEnding(end: Date, count: number) { const days: Date[] = []; const cursor = new Date(end); cursor.setHours(12, 0, 0, 0); while (days.length < count) { const weekday = cursor.getDay(); if (weekday !== 0 && weekday !== 6) days.unshift(new Date(cursor)); cursor.setDate(cursor.getDate() - 1); } return days; }
function buildRange(mode: ReportMode, selected: Date) { const days = operationalDaysEnding(selected, mode === 'daily' ? 1 : mode === 'weekly' ? 5 : 20); const start = days[0]; const end = days[days.length - 1]; return { start: new Date(start.getFullYear(), start.getMonth(), start.getDate(), 0, 0, 0), end: new Date(end.getFullYear(), end.getMonth(), end.getDate(), 23, 59, 59), label: mode === 'daily' ? dateFormatter.format(start) : `${dateFormatter.format(start)} — ${dateFormatter.format(end)}` }; }
function statusLabel(value: string) { return ({ pending: 'Pendiente', preparing: 'En preparación', ready: 'Listo para recoger', delivered: 'Entregado', cancelled: 'Cancelado', confirmed: 'Confirmado', rejected: 'Rechazado' } as Record<string, string>)[value] ?? value; }
function paymentLabel(value: string) { return ({ nequi: 'Nequi', 'bre-b': 'Bre-B', cash: 'Efectivo', bancolombia: 'Bancolombia', daviplata: 'Daviplata' } as Record<string, string>)[value] ?? value; }
function toSalesRows(orders: Order[]): Array<Array<string | number>> { return orders.map((order) => [order.order_number, dateFormatter.format(new Date(order.created_at)), timeFormatter.format(new Date(order.created_at)), order.user?.full_name ?? 'Sin cliente', order.user?.email ?? '', order.user?.ti ?? '', statusLabel(order.status), statusLabel(order.payment_status), paymentLabel(order.payment_method), order.pickup_code ?? '', order.payment_reference ?? '', Number(order.total), Number(order.order_items?.length ?? 0), Number(order.order_items?.reduce((sum, item) => sum + item.quantity, 0) ?? 0), Number(order.estimated_minutes ?? 0)]); }
function toDetailRows(orders: Order[]): Array<Array<string | number>> { return orders.flatMap((order) => (order.order_items ?? []).map((item) => [order.order_number, dateFormatter.format(new Date(order.created_at)), timeFormatter.format(new Date(order.created_at)), item.product?.name ?? 'Producto no disponible', item.product?.category?.name ?? 'Sin categoría', Number(item.price), Number(item.quantity), Number(item.price) * Number(item.quantity), Number(item.product?.stock ?? 0), order.user?.full_name ?? 'Sin cliente'])); }
function toRedemptionRows(redemptions: SalesRedemptionExport[]): Array<Array<string | number>> { return redemptions.map((redemption) => [redemption.redemption_code, dateFormatter.format(new Date(redemption.created_at)), redemption.user?.full_name ?? 'Estudiante', redemption.user?.email ?? '', redemption.reward?.title ?? 'Recompensa', redemption.reward?.product?.name ?? '', Number(redemption.points_spent), statusLabel(redemption.status)]); }

export function AdminReports() {
  const [mode, setMode] = useState<ReportMode>('daily');
  const [selectedDate, setSelectedDate] = useState(() => dateKey(new Date()));
  const [orders, setOrders] = useState<Order[]>([]);
  const [redemptions, setRedemptions] = useState<SalesRedemptionExport[]>([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const selected = useMemo(() => parseInputDate(selectedDate), [selectedDate]);
  const range = useMemo(() => buildRange(mode, selected), [mode, selected]);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const client = requireSupabaseClient(); const startIso = range.start.toISOString(); const endIso = range.end.toISOString();
      const [{ data: orderData, error: orderError }, { data: redemptionData, error: redemptionError }] = await Promise.all([
        client.from('orders').select('*, order_items(*, product:products(*, category:categories(*))), user:profiles(*)').gte('created_at', startIso).lte('created_at', endIso).order('created_at', { ascending: true }),
        client.from('loyalty_redemptions').select('id,redemption_code,points_spent,status,created_at,admin_hidden,reward:loyalty_rewards(title,product:products(name)),user:profiles!loyalty_redemptions_user_id_fkey(full_name,email)').gte('created_at', startIso).lte('created_at', endIso).order('created_at', { ascending: true }),
      ]);
      if (orderError) throw orderError; if (redemptionError) throw redemptionError;
      setOrders((orderData ?? []) as unknown as Order[]); setRedemptions((redemptionData ?? []) as unknown as SalesRedemptionExport[]);
    } catch (error) { toast.error(error instanceof Error ? error.message : 'No se pudo cargar el informe.'); setOrders([]); setRedemptions([]); }
    finally { setLoading(false); }
  }, [range]);
  useEffect(() => { void load(); }, [load]);
  const confirmedOrders = useMemo(() => orders.filter((order) => order.payment_status === 'confirmed' && order.status !== 'cancelled'), [orders]);
  const totalSales = useMemo(() => confirmedOrders.reduce((sum, order) => sum + Number(order.total), 0), [confirmedOrders]);
  const totalUnits = useMemo(() => confirmedOrders.reduce((sum, order) => sum + Number(order.order_items?.reduce((units, item) => units + item.quantity, 0) ?? 0), 0), [confirmedOrders]);
  const averageTicket = confirmedOrders.length ? totalSales / confirmedOrders.length : 0;
  const salesRows = useMemo(() => toSalesRows(orders), [orders]);
  const detailRows = useMemo(() => toDetailRows(orders), [orders]);
  const redemptionRows = useMemo(() => toRedemptionRows(redemptions), [redemptions]);
  const dayBreakdown = useMemo(() => operationalDaysEnding(selected, mode === 'daily' ? 1 : mode === 'weekly' ? 5 : 20).map((day) => { const key = dateKey(day); const dayOrders = orders.filter((order) => dateKey(new Date(order.created_at)) === key); const confirmed = dayOrders.filter((order) => order.payment_status === 'confirmed' && order.status !== 'cancelled'); return { key, label: day.toLocaleDateString('es-CO', { weekday: 'short', day: '2-digit', month: 'short' }), orders: dayOrders.length, sales: confirmed.reduce((sum, order) => sum + Number(order.total), 0), units: confirmed.reduce((sum, order) => sum + Number(order.order_items?.reduce((units, item) => units + item.quantity, 0) ?? 0), 0) }; }), [mode, orders, selected]);
  const weeklyBreakdown = useMemo(() => mode === 'monthly' ? Array.from({ length: 4 }, (_, index) => { const slice = dayBreakdown.slice(index * 5, index * 5 + 5); return { label: `Semana ${index + 1}`, orders: slice.reduce((sum, day) => sum + day.orders, 0), sales: slice.reduce((sum, day) => sum + day.sales, 0), units: slice.reduce((sum, day) => sum + day.units, 0) }; }) : [], [dayBreakdown, mode]);
  const handleDownload = () => { if (!orders.length) { toast.info('No hay datos para exportar en este período.'); return; } setExporting(true); try { const workbook = buildActiveSalesWorkbook(orders, redemptions, { includeHidden: true }); XLSX.writeFile(workbook, `quickbite-informe-${mode}-${selectedDate}.xlsx`, { compression: true }); toast.success('Informe descargado conservando la estructura actual de Excel.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'No se pudo generar el Excel.'); } finally { setExporting(false); } };
  const maxSales = Math.max(...dayBreakdown.map((day) => day.sales), 1);
  return <div className="mx-auto max-w-7xl">
    <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><BarChart3 className="h-9 w-9 text-blue-700" /><h1 className="text-4xl font-bold text-blue-900">Informes</h1></div><p className="mt-2 text-lg text-slate-600">Consulta el historial de ventas manteniendo la misma estructura de Excel.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button><Button onClick={handleDownload} disabled={loading || exporting || !orders.length} className="bg-green-600 text-white hover:bg-green-700"><FileSpreadsheet className="mr-2 h-4 w-4" />{exporting ? 'Generando...' : 'Descargar Excel'}</Button></div></div>
    <section className="mb-6 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex rounded-2xl bg-slate-100 p-1">{([['daily', 'Diario'], ['weekly', 'Semanal'], ['monthly', 'Mensual']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setMode(value)} className={`rounded-xl px-5 py-2.5 text-sm font-bold transition ${mode === value ? 'bg-blue-700 text-white shadow' : 'text-slate-600 hover:bg-white'}`}>{label}</button>)}</div><label className="flex items-center gap-3 text-sm font-semibold text-slate-700"><CalendarDays className="h-5 w-5 text-blue-700" /><span>Fecha de cierre</span><input type="date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 font-medium outline-none focus:ring-2 focus:ring-blue-200" /></label></div><p className="mt-3 text-sm text-slate-500">{mode === 'daily' ? 'Un día operativo.' : mode === 'weekly' ? 'Agrupa 5 días operativos (lunes a viernes).' : 'Agrupa 4 semanas operativas de 5 días cada una.'}</p></section>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={TrendingUp} label="Ventas confirmadas" value={currency.format(totalSales)} /><Kpi icon={ShoppingBag} label="Pedidos" value={String(orders.length)} /><Kpi icon={FileSpreadsheet} label="Unidades vendidas" value={String(totalUnits)} /><Kpi icon={BarChart3} label="Ticket promedio" value={currency.format(averageTicket)} /></div>
    <section className="mb-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-900">Desglose del período</h2><p className="text-sm text-slate-500">{range.label}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{mode === 'daily' ? '1 día' : mode === 'weekly' ? '5 días' : '4 semanas / 20 días'}</span></div>{mode === 'monthly' ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{weeklyBreakdown.map((week) => <div key={week.label} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="font-bold text-slate-900">{week.label}</p><p className="mt-2 text-xl font-black text-blue-900">{currency.format(week.sales)}</p><p className="mt-1 text-xs text-slate-500">{week.orders} pedidos · {week.units} unidades</p></div>)}</div> : <div className="space-y-3">{dayBreakdown.map((day) => <div key={day.key} className="grid grid-cols-[90px_1fr_110px] items-center gap-3"><span className="text-sm font-bold capitalize text-slate-700">{day.label}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(3, (day.sales / maxSales) * 100)}%` }} /></div><div className="text-right text-sm font-bold text-slate-800">{currency.format(day.sales)}</div></div>)}</div>}</section>
    <ReportSection title="Ventas" subtitle="Misma estructura de la hoja “Ventas” del Excel actual.">{loading ? <Empty text="Cargando informe..." /> : salesRows.length === 0 ? <Empty text="No hay ventas en este período." /> : <ReportTable headers={salesHeaders} rows={salesRows} currencyColumns={[11]} />}</ReportSection>
    <ReportSection title="Detalle de productos" subtitle="Misma estructura de la hoja “Detalle de productos”.">{detailRows.length === 0 ? <Empty text="No hay detalles de productos." /> : <ReportTable headers={detailHeaders} rows={detailRows} currencyColumns={[5, 7]} />}</ReportSection>
    <ReportSection title="Canjes" subtitle="Misma estructura de la hoja “Canjes”.">{redemptionRows.length === 0 ? <Empty text="No hay canjes en este período." /> : <ReportTable headers={redemptionHeaders} rows={redemptionRows} />}</ReportSection>
  </div>;
}
function Kpi({ icon: Icon, label, value }: { icon: typeof TrendingUp; label: string; value: string }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><Icon className="h-6 w-6 text-blue-600" /></div><p className="text-2xl font-black text-slate-900">{value}</p></div>; }
function ReportSection({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="mb-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-xl font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="p-10 text-center text-slate-500">{text}</div>; }
function ReportTable({ headers, rows, currencyColumns = [] }: { headers: string[]; rows: Array<Array<string | number>>; currencyColumns?: number[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-green-900 text-xs uppercase text-white"><tr>{headers.map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, rowIndex) => <tr key={`${rowIndex}-${String(row[0])}`} className={rowIndex % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>{row.map((value, columnIndex) => <td key={`${rowIndex}-${columnIndex}`} className="px-4 py-3 align-top">{currencyColumns.includes(columnIndex) && typeof value === 'number' ? currency.format(value) : String(value ?? '')}</td>)}</tr>)}</tbody></table></div>; }
