import { useCallback, useEffect, useState } from 'react';
import { Wallet, Check, X, RefreshCw, MessageSquare } from 'lucide-react';
import { toast } from 'sonner';
import { requireSupabaseClient } from '../../../lib/supabase';

type RequestRow = { id: string; user_id: string; amount: number; method: string; reference: string | null; comment: string | null; status: string; rejection_reason: string | null; created_at: string; reviewed_at: string | null; profile?: { full_name: string; email: string } | null };
const money = (n: number) => Number(n).toLocaleString('es-CO');

export function AdminWalletTopups() {
  const [requests, setRequests] = useState<RequestRow[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { const client = requireSupabaseClient(); const { data, error } = await client.from('wallet_topup_requests').select('id,user_id,amount,method,reference,comment,status,rejection_reason,created_at,reviewed_at').order('created_at', { ascending: false }).limit(100); if (error) throw error; const rows = (data ?? []) as RequestRow[]; const ids = [...new Set(rows.map((r) => r.user_id))]; if (ids.length) { const { data: profiles, error: profileError } = await client.from('profiles').select('id,full_name,email').in('id', ids); if (profileError) throw profileError; setRequests(rows.map((r) => ({ ...r, profile: (profiles ?? []).find((p) => p.id === r.user_id) ?? null }))); } else setRequests(rows); }, []);
  useEffect(() => { void load().catch((e) => toast.error(e instanceof Error ? e.message : 'No se pudieron cargar las recargas.')).finally(() => setLoading(false)); }, [load]);
  const approve = async (id: string) => { setBusy(id); try { const { error } = await requireSupabaseClient().rpc('approve_wallet_topup', { p_request_id: id }); if (error) throw error; toast.success('Recarga aprobada y saldo actualizado.'); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : 'No se pudo aprobar la recarga.'); } finally { setBusy(null); } };
  const reject = async (id: string) => { const reason = window.prompt('Motivo del rechazo (opcional):') ?? ''; setBusy(id); try { const { error } = await requireSupabaseClient().rpc('reject_wallet_topup', { p_request_id: id, p_reason: reason }); if (error) throw error; toast.success('Recarga rechazada.'); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : 'No se pudo rechazar la recarga.'); } finally { setBusy(null); } };
  const pending = requests.filter((r) => r.status === 'pending');
  return <div className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Finanzas</p><h1 className="text-3xl font-black">Recargas de billetera</h1><p className="text-sm text-slate-600">Revisa cada solicitud, consulta su comentario y aprueba o rechaza de forma segura.</p></div><button onClick={() => void load()} className="rounded-full bg-white p-3 shadow-sm" aria-label="Actualizar"><RefreshCw className="h-4 w-4"/></button></header><div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Wallet className="h-6 w-6 text-emerald-700"/><div><p className="font-black">Pendientes</p><p className="text-sm text-slate-500">{pending.length} solicitudes por revisar</p></div></div></div>{loading ? <p>Cargando…</p> : requests.length === 0 ? <div className="rounded-3xl bg-white p-8 text-center">No hay solicitudes de recarga.</div> : <div className="space-y-3">{requests.map((r) => <article key={r.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-black">{r.profile?.full_name ?? 'Usuario'}</p><p className="text-sm text-slate-500">{r.profile?.email ?? r.user_id}</p><p className="mt-2 text-xs text-slate-400">{new Date(r.created_at).toLocaleString('es-CO')} · {r.method}{r.reference ? ` · Ref. ${r.reference}` : ''}</p></div><div className="text-right"><p className="text-2xl font-black text-emerald-700">${money(Number(r.amount))}</p><span className="text-xs font-black uppercase text-slate-500">{r.status}</span></div></div>{r.comment && <div className="mt-4 flex gap-3 rounded-2xl bg-slate-50 p-4"><MessageSquare className="mt-0.5 h-4 w-4 shrink-0 text-slate-500"/><div><p className="text-xs font-black uppercase tracking-wide text-slate-500">Comentario</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{r.comment}</p></div></div>}{r.status === 'pending' && <div className="mt-4 flex gap-2"><button disabled={busy === r.id} onClick={() => void approve(r.id)} className="inline-flex items-center gap-2 rounded-full bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50"><Check className="h-4 w-4"/>Aprobar</button><button disabled={busy === r.id} onClick={() => void reject(r.id)} className="inline-flex items-center gap-2 rounded-full bg-rose-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50"><X className="h-4 w-4"/>Rechazar</button></div>}{r.rejection_reason && <p className="mt-3 rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">Motivo: {r.rejection_reason}</p>}</article>)}</div>}</div></div>;
}
