import { useEffect, useMemo, useState } from 'react';
import * as XLSX from '@redoper1/xlsx-js-style';
import { BarChart3, CalendarDays, FileSpreadsheet, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { requireSupabaseClient, type Order } from '../../../lib/supabase';
import { Button } from '../../components/ui/button';
import { Card } from '../../components/ui/card';

type Mode='daily'|'weekly'|'monthly';
type Redemption={id:string;code:string;date:string;student:string;reward:string;points:number;status:string};
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money=(n:number)=>n.toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
function businessDays(end:Date,count:number){const out:Date[]=[];const d=new Date(end);d.setHours(12,0,0,0);while(out.length<count){if(d.getDay()!==0&&d.getDay()!==6)out.unshift(new Date(d));d.setDate(d.getDate()-1);}return out;}
function AdminReportsStable(){const[mode,setMode]=useState<Mode>('daily');const[selectedDate,setSelectedDate]=useState(key(new Date()));const[orders,setOrders]=useState<Order[]>([]);const[reds,setReds]=useState<Redemption[]>([]);const[loading,setLoading]=useState(true);const selected=useMemo(()=>{const[a,b,c]=selectedDate.split('-').map(Number);return new Date(a,b-1,c,12)},[selectedDate]);const days=useMemo(()=>businessDays(selected,mode==='daily'?1:mode==='weekly'?5:20),[mode,selected]);const start=new Date(days[0].getFullYear(),days[0].getMonth(),days[0].getDate());const end=new Date(days.at(-1)!.getFullYear(),days.at(-1)!.getMonth(),days.at(-1)!.getDate(),23,59,59);
 const load=async()=>{setLoading(true);try{const c=requireSupabaseClient();const[o,r]=await Promise.all([c.from('orders').select('*,order_items(*,product:products(*,category:categories(*))),user:profiles(*)').gte('created_at',start.toISOString()).lte('created_at',end.toISOString()).order('created_at'),c.from('loyalty_redemptions').select('id,redemption_code,points_spent,status,created_at,reward:loyalty_rewards(title),user:profiles!loyalty_redemptions_user_id_fkey(full_name)').gte('created_at',start.toISOString()).lte('created_at',end.toISOString()).order('created_at')]);if(o.error)throw o.error;if(r.error)throw r.error;setOrders((o.data??[]) as unknown as Order[]);setReds((r.data??[]).map((x:any)=>({id:x.id,code:x.redemption_code,date:new Date(x.created_at).toLocaleString('es-CO'),student:Array.isArray(x.user)?x.user[0]?.full_name??'Estudiante':x.user?.full_name??'Estudiante',reward:Array.isArray(x.reward)?x.reward[0]?.title??'Recompensa':x.reward?.title??'Recompensa',points:Number(x.points_spent??0),status:x.status??''})));}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar el informe.');setOrders([]);setReds([]);}finally{setLoading(false);}};useEffect(()=>{void load();},[start.getTime(),end.getTime()]);
 const confirmed=orders.filter(o=>o.payment_status==='confirmed');const total=confirmed.reduce((s,o)=>s+Number(o.total),0);const units=confirmed.reduce((s,o)=>s+(o.order_items??[]).reduce((x,i)=>x+i.quantity,0),0);const avg=confirmed.length?total/confirmed.length:0;
 const exportExcel=async()=>{if(!orders.length&&!reds.length){toast.info('No hay datos para exportar.');return;}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Resumen'],['Ventas confirmadas',total],['Pedidos',confirmed.length],['Unidades vendidas',units],['Ticket promedio',avg]]),'Resumen');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Pedido','Fecha','Cliente','Pago','Total'],...orders.map(o=>[o.order_number,new Date(o.created_at).toLocaleString('es-CO'),o.user?.full_name??'',o.payment_status,Number(o.total)])]),'Ventas');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Pedido','Producto','Cantidad','Precio','Subtotal'],...orders.flatMap(o=>(o.order_items??[]).map(i=>[o.order_number,i.product?.name??'',i.quantity,Number(i.price),Number(i.price)*i.quantity]))]),'Detalle de productos');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Código','Fecha','Estudiante','Recompensa','Puntos','Estado'],...reds.map(r=>[r.code,r.date,r.student,r.reward,r.points,r.status])]),'Canjes');XLSX.writeFile(wb,`QuickBite-informe-${mode}-${selectedDate}.xlsx`,{compression:true});try{const ids=reds.map(r=>r.id);if(ids.length){const{error}=await requireSupabaseClient().from('loyalty_redemptions').delete().in('id',ids);if(error)throw error;}setReds([]);toast.success('Excel descargado. Los canjes incluidos fueron eliminados del período.');}catch(e){toast.warning(e instanceof Error?`Excel descargado, pero los canjes no pudieron eliminarse: ${e.message}`:'Excel descargado, pero los canjes no pudieron eliminarse.');}};
 return <div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-3"><BarChart3 className="h-8 w-8 text-blue-700"/><h1 className="text-4xl font-black text-blue-900">Informes</h1></div><p className="mt-2 text-slate-600">Diario · Semanal · Mensual</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button><Button onClick={()=>void exportExcel()} className="bg-green-600 text-white"><FileSpreadsheet className="mr-2 h-4 w-4"/>Descargar Excel</Button></div></div><Card className="mb-6 p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-1 rounded-xl bg-slate-100 p-1">{([['daily','Diario'],['weekly','Semanal'],['monthly','Mensual']] as const).map(([v,l])=><button type="button" key={v} onClick={()=>setMode(v)} className={`rounded-lg px-4 py-2 font-bold ${mode===v?'bg-blue-700 text-white':'text-slate-600'}`}>{l}</button>)}</div><label className="flex items-center gap-2 text-sm font-semibold"><CalendarDays className="h-4 w-4"/>Fecha<input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="rounded-lg border px-3 py-2"/></label></div></Card><div className="mb-6 grid gap-4 md:grid-cols-3"><K label="Ventas" v={money(total)}/><K label="Unidades" v={String(units)}/><K label="Ticket promedio" v={money(avg)}/></div><S title="Ventas" rows={orders.map(o=>[o.order_number,new Date(o.created_at).toLocaleString('es-CO'),o.user?.full_name??'',o.payment_status,Number(o.total)])} h={['Pedido','Fecha','Cliente','Pago','Total']}/><S title="Detalle de productos" rows={orders.flatMap(o=>(o.order_items??[]).map(i=>[o.order_number,i.product?.name??'',i.quantity,Number(i.price),Number(i.price)*i.quantity]))} h={['Pedido','Producto','Cantidad','Precio','Subtotal']}/><S title="Canjes" rows={reds.map(r=>[r.code,r.date,r.student,r.reward,r.points,r.status])} h={['Código','Fecha','Estudiante','Recompensa','Puntos','Estado']}/></div>}
const K=({label,v}:{label:string;v:string})=><Card className="p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-blue-900">{v}</p></Card>;const S=({title,rows,h}:{title:string;rows:unknown[][];h:string[]})=><Card className="mb-6 overflow-hidden"><div className="border-b p-4"><h2 className="text-xl font-bold">{title}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-green-900 text-white"><tr>{h.map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className={i%2?'bg-slate-50':''}>{r.map((x,j)=><td key={j} className="px-4 py-3">{String(x??'')}</td>)}</tr>):<tr><td colSpan={h.length} className="p-8 text-center text-slate-500">No hay datos.</td></tr>}</tbody></table></div></Card>;
export default AdminReportsStable;
