import { useEffect, useMemo, useState } from 'react';
import * as XLSX from '@redoper1/xlsx-js-style';
import { BarChart3, CalendarDays, FileSpreadsheet, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { requireSupabaseClient, type Order } from '../../../lib/supabase';
import { Button } from '../../components/ui/button';
import { Card } from '../../components/ui/card';

type Mode = 'daily' | 'weekly' | 'monthly';
type RedemptionRow = { code: string; date: string; student: string; reward: string; points: number; status: string };
const keyOf = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money = (n: number) => n.toLocaleString('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 });
function daysEnding(end: Date, count: number) { const out: Date[] = []; const d = new Date(end); d.setHours(12,0,0,0); while (out.length < count) { if (![0,6].includes(d.getDay())) out.unshift(new Date(d)); d.setDate(d.getDate()-1); } return out; }
function rangeFor(mode: Mode, selected: Date) { const days = daysEnding(selected, mode === 'daily' ? 1 : mode === 'weekly' ? 5 : 20); return { start: new Date(days[0].getFullYear(), days[0].getMonth(), days[0].getDate()), end: new Date(days.at(-1)!.getFullYear(), days.at(-1)!.getMonth(), days.at(-1)!.getDate(), 23,59,59), days }; }

export function AdminReportsStable() {
  const [mode,setMode]=useState<Mode>('daily');
  const [selectedDate,setSelectedDate]=useState(keyOf(new Date()));
  const [orders,setOrders]=useState<Order[]>([]);
  const [redemptions,setRedemptions]=useState<RedemptionRow[]>([]);
  const [loading,setLoading]=useState(true);
  const selected=useMemo(()=>{const [y,m,d]=selectedDate.split('-').map(Number);return new Date(y,m-1,d,12)},[selectedDate]);
  const range=useMemo(()=>rangeFor(mode,selected),[mode,selected]);
  const load=async()=>{setLoading(true);try{const c=requireSupabaseClient();const {data:od,error:oe}=await c.from('orders').select('*,order_items(*,product:products(*,category:categories(*))),user:profiles(*)').gte('created_at',range.start.toISOString()).lte('created_at',range.end.toISOString()).order('created_at');if(oe)throw oe;const {data:rd,error:re}=await c.from('loyalty_redemptions').select('id,redemption_code,points_spent,status,created_at,reward:loyalty_rewards(title),user:profiles!loyalty_redemptions_user_id_fkey(full_name)').gte('created_at',range.start.toISOString()).lte('created_at',range.end.toISOString()).order('created_at');if(re)throw re;setOrders((od??[]) as unknown as Order[]);setRedemptions((rd??[]).map((r:any)=>({code:r.redemption_code,date:new Date(r.created_at).toLocaleString('es-CO'),student:Array.isArray(r.user)?r.user[0]?.full_name??'Estudiante':r.user?.full_name??'Estudiante',reward:Array.isArray(r.reward)?r.reward[0]?.title??'Recompensa':r.reward?.title??'Recompensa',points:Number(r.points_spent??0),status:r.status??''})));}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar el informe.');setOrders([]);setRedemptions([]);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[range.start.getTime(),range.end.getTime()]);
  const confirmed=orders.filter(o=>o.payment_status==='confirmed');
  const total=confirmed.reduce((s,o)=>s+Number(o.total),0); const units=confirmed.reduce((s,o)=>s+(o.order_items??[]).reduce((x,i)=>x+i.quantity,0),0); const avg=confirmed.length?total/confirmed.length:0;
  const exportExcel=()=>{if(!orders.length&&!redemptions.length){toast.info('No hay datos para exportar.');return;}const wb=XLSX.utils.book_new();const sales=orders.map(o=>[o.order_number,new Date(o.created_at).toLocaleString('es-CO'),o.user?.full_name??'',o.payment_status,Number(o.total)]);const details=orders.flatMap(o=>(o.order_items??[]).map(i=>[o.order_number,i.product?.name??'',i.quantity,Number(i.price),Number(i.price)*i.quantity]));const reds=redemptions.map(r=>[r.code,r.date,r.student,r.reward,r.points,r.status]);XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Resumen'],['Ventas confirmadas',total],['Pedidos',confirmed.length],['Unidades',units],['Ticket promedio',avg]]),'Resumen');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Pedido','Fecha','Cliente','Estado pago','Total'],...sales]),'Ventas');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Pedido','Producto','Cantidad','Precio','Subtotal'],...details]),'Detalle de productos');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Código','Fecha','Estudiante','Recompensa','Puntos','Estado'],...reds]),'Canjes');XLSX.writeFile(wb,`QuickBite-informe-${mode}-${selectedDate}.xlsx`,{compression:true});void (async()=>{try{const ids=await requireSupabaseClient().from('loyalty_redemptions').select('id').gte('created_at',range.start.toISOString()).lte('created_at',range.end.toISOString());if(ids.error)throw ids.error;const list=(ids.data??[]).map((r:any)=>r.id);if(list.length)await requireSupabaseClient().from('loyalty_redemptions').delete().in('id',list);setRedemptions([]);toast.success('Excel descargado y canjes del período eliminados.');}catch(e){toast.warning(e instanceof Error?`Excel descargado, pero no se pudieron eliminar los canjes: ${e.message}`:'Excel descargado, pero no se pudieron eliminar los canjes.');}})();};
  return <div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-3"><BarChart3 className="h-8 w-8 text-blue-700"/><h1 className="text-4xl font-black text-blue-900">Informes</h1></div><p className="mt-2 text-slate-600">Histórico administrativo: diario, semanal y mensual.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button><Button onClick={exportExcel} disabled={loading} className="bg-green-600 text-white hover:bg-green-700"><FileSpreadsheet className="mr-2 h-4 w-4"/>Descargar Excel</Button></div></div><Card className="mb-6 p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-1 rounded-xl bg-slate-100 p-1">{([['daily','Diario'],['weekly','Semanal'],['monthly','Mensual']] as const).map(([v,l])=><button key={v} onClick={()=>setMode(v)} className={`rounded-lg px-4 py-2 font-bold ${mode===v?'bg-blue-700 text-white':'text-slate-600'}`}>{l}</button>)}</div><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CalendarDays className="h-4 w-4"/>Fecha<input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="rounded-lg border px-3 py-2"/></label></div><p className="mt-3 text-sm text-slate-500">{mode==='daily'?'1 día':mode==='weekly'?'5 días operativos':'4 semanas de 5 días (20 días)'}</p></Card><div className="mb-6 grid gap-4 md:grid-cols-3"><Kpi label="Ventas confirmadas" value={money(total)}/><Kpi label="Unidades vendidas" value={String(units)}/><Kpi label="Ticket promedio" value={money(avg)}/></div><Section title="Ventas" headers={['Pedido','Fecha','Cliente','Pago','Total']} rows={orders.map(o=>[o.order_number,new Date(o.created_at).toLocaleString('es-CO'),o.user?.full_name??'',o.payment_status,Number(o.total)])}/><Section title="Detalle de productos" headers={['Pedido','Producto','Cantidad','Precio','Subtotal']} rows={orders.flatMap(o=>(o.order_items??[]).map(i=>[o.order_number,i.product?.name??'',i.quantity,Number(i.price),Number(i.price)*i.quantity]))}/><Section title="Canjes" headers={['Código','Fecha','Estudiante','Recompensa','Puntos','Estado']} rows={redemptions.map(r=>[r.code,r.date,r.student,r.reward,r.points,r.status])}/></div>;
}
function Kpi({label,value}:{label:string;value:string}){return <Card className="p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-blue-900">{value}</p></Card>}
function Section({title,headers,rows}:{title:string;headers:string[];rows:unknown[][]}){return <Card className="mb-6 overflow-hidden"><div className="border-b p-4"><h2 className="text-xl font-bold text-slate-900">{title}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-green-900 text-white"><tr>{headers.map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.length===0?<tr><td colSpan={headers.length} className="p-8 text-center text-slate-500">No hay datos.</td></tr>:rows.map((r,i)=><tr key={i} className={i%2?'bg-slate-50':'bg-white'}>{r.map((v,j)=><td key={j} className="px-4 py-3">{String(v??'')}</td>)}</tr>)}</tbody></table></div></Card>}
