import { useMemo, useState } from 'react';
import { useDataStore } from '../../../store/dataStore';
import { Card } from '../../components/ui/card';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { CheckCircle, XCircle, Clock, CreditCard, MessageSquare } from 'lucide-react';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { toast } from 'sonner';

const fmt = (value: number) => value.toLocaleString('es-CO');

export function AdminPayments() {
  const { orders, moderateOrderPayment } = useDataStore();
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const activeOrders = useMemo(() => orders.filter((order) => !order.admin_hidden), [orders]);
  const filteredOrders = useMemo(() => { let filtered = activeOrders.slice().sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()); if (filterStatus !== 'all') filtered = filtered.filter((o) => o.payment_status === filterStatus); return filtered; }, [activeOrders, filterStatus]);
  const stats = useMemo(() => ({ pending: activeOrders.filter((o) => o.payment_status === 'pending').length, confirmed: activeOrders.filter((o) => o.payment_status === 'confirmed').length, rejected: activeOrders.filter((o) => o.payment_status === 'rejected').length, totalConfirmed: activeOrders.filter((o) => o.payment_status === 'confirmed').reduce((sum, o) => sum + o.total, 0) }), [activeOrders]);
  const handleConfirmPayment = async (orderId: string) => { try { await moderateOrderPayment(orderId, 'approve'); toast.success('Pago confirmado exitosamente'); } catch (error) { toast.error(error instanceof Error ? error.message : 'No se pudo confirmar el pago'); } };
  const handleRejectPayment = async (orderId: string) => { try { await moderateOrderPayment(orderId, 'reject'); toast.success('Pago rechazado y pedido cancelado. El stock fue restaurado.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'No se pudo rechazar el pago'); } };
  const getPaymentStatusBadge = (status: string) => { const config = { pending: { label: 'Pendiente', className: 'bg-amber-500 text-white' }, confirmed: { label: 'Confirmado', className: 'bg-green-600 text-white' }, rejected: { label: 'Rechazado', className: 'bg-red-500 text-white' } }; const statusConfig = config[status as keyof typeof config] || config.pending; return <Badge className={statusConfig.className}>{statusConfig.label}</Badge>; };
  return <div>
    <div className="mb-8"><h1 className="mb-2 text-4xl font-bold text-blue-900">Gestión de pagos</h1><p className="text-lg text-gray-600">Confirma o rechaza pagos antes de que el pedido pase a Gestión de pedidos.</p></div>
    <div className="mb-8 grid grid-cols-1 gap-6 md:grid-cols-4"><Card className="border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-2 flex items-center justify-between"><Clock className="h-8 w-8 text-amber-500"/><span className="text-3xl font-bold">{stats.pending}</span></div><p className="text-sm font-medium text-slate-500">Pagos pendientes</p></Card><Card className="border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-2 flex items-center justify-between"><CheckCircle className="h-8 w-8 text-green-600"/><span className="text-3xl font-bold">{stats.confirmed}</span></div><p className="text-sm font-medium text-slate-500">Pagos confirmados</p></Card><Card className="border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-2 flex items-center justify-between"><XCircle className="h-8 w-8 text-red-600"/><span className="text-3xl font-bold">{stats.rejected}</span></div><p className="text-sm font-medium text-slate-500">Pagos rechazados</p></Card><Card className="border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-2 flex items-center justify-between"><CreditCard className="h-8 w-8 text-blue-600"/><span className="text-2xl font-bold">${fmt(stats.totalConfirmed)}</span></div><p className="text-sm font-medium text-slate-500">Total confirmado</p></Card></div>
    <Card className="mb-6 border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center"><label className="font-medium text-gray-700">Filtrar por estado:</label><Select value={filterStatus} onValueChange={setFilterStatus}><SelectTrigger className="w-64"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los pagos</SelectItem><SelectItem value="pending">Pendientes</SelectItem><SelectItem value="confirmed">Confirmados</SelectItem><SelectItem value="rejected">Rechazados</SelectItem></SelectContent></Select><div className="md:ml-auto"><span className="text-sm text-gray-600">Total: <span className="font-bold text-blue-900">{filteredOrders.length}</span> pago(s)</span></div></div></Card>
    {filteredOrders.length === 0 ? <Card className="border border-slate-200 bg-white p-12 text-center shadow-sm"><CreditCard className="mx-auto mb-4 h-16 w-16 text-gray-300"/><p className="text-lg text-gray-500">No hay pagos para mostrar</p></Card> : <div className="space-y-4">{filteredOrders.map((order) => { const comment = (order.student_comment ?? order.notes ?? '').trim(); return <Card key={order.id} className="border border-slate-200 bg-white p-6 shadow-sm transition hover:shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex items-center gap-3"><h3 className="text-2xl font-bold text-green-700">{order.order_number}</h3>{getPaymentStatusBadge(order.payment_status)}</div><p className="mb-2 text-sm text-gray-600">{format(new Date(order.created_at), "d 'de' MMMM, yyyy - HH:mm", { locale: es })}</p><div className="flex items-center gap-4 text-sm"><div><span className="text-gray-600">Método: </span><span className="font-medium capitalize">{order.payment_method === 'cash' ? 'Efectivo' : order.payment_method}</span></div><div><span className="text-gray-600">Artículos: </span><span className="font-medium">{order.order_items?.reduce((sum, item) => sum + item.quantity, 0) || 0}</span></div></div></div><div className="text-right"><p className="mb-1 text-sm text-gray-600">Total</p><p className="mb-3 text-3xl font-bold text-blue-900">${fmt(order.total)}</p>{order.payment_status === 'pending' && <div className="flex gap-2"><Button size="sm" onClick={() => handleConfirmPayment(order.id)} className="bg-green-600 text-white hover:bg-green-700"><CheckCircle className="mr-2 h-4 w-4"/>Confirmar</Button><Button size="sm" variant="destructive" onClick={() => handleRejectPayment(order.id)}><XCircle className="mr-2 h-4 w-4"/>Rechazar</Button></div>}</div></div><div className="mt-4 border-t border-gray-200 pt-4"><p className="mb-2 text-sm font-medium text-gray-700">Resumen del pedido:</p><div className="flex flex-wrap gap-2">{order.order_items?.map((item) => <Badge key={item.id} variant="outline" className="bg-gray-50">{item.quantity}x {item.product?.name ?? 'Producto'}</Badge>)}</div>{comment && <div className="mt-3 flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-3"><MessageSquare className="mt-0.5 h-4 w-4 shrink-0 text-blue-700"/><div><p className="text-xs font-bold text-blue-800">Comentario del estudiante</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{comment}</p></div></div>}</div></Card>; })}</div>}
  </div>;
}
