import { useEffect, useMemo, useRef, useState } from 'react';
import { Check, ChevronDown, Edit3, RotateCcw, Sparkles, X } from 'lucide-react';
import { useVisualTheme } from '../../contexts/VisualThemeProvider';
import { sanitizeVisualElementStyle, sanitizeVisualSettings, type VisualElementStyle, type VisualInterfaceScope, type VisualSettingsDraft } from '../../../types/visualSettings';

type Props = { scope: VisualInterfaceScope };
type Selected = { element: HTMLElement; selector: string; label: string; tag: string } | null;
type Field = { key: keyof VisualElementStyle; label: string; type: 'color' | 'text' | 'textarea' | 'select'; options?: string[] };
const PROTECTED_SELECTOR = '[data-qb-visual-editor], [data-qb-visual-editor-panel]';
const CLICK_DELAY = 220;

const FIELDS: Field[] = [
  { key: 'textContent', label: 'Texto visible', type: 'textarea' },
  { key: 'backgroundColor', label: 'Color de fondo', type: 'color' },
  { key: 'backgroundImage', label: 'Fondo / gradiente', type: 'text' },
  { key: 'color', label: 'Color del texto', type: 'color' },
  { key: 'fontFamily', label: 'Familia tipográfica', type: 'text' },
  { key: 'fontSize', label: 'Tamaño', type: 'text' },
  { key: 'fontWeight', label: 'Peso', type: 'select', options: ['400', '500', '600', '700', '800', '900'] },
  { key: 'lineHeight', label: 'Altura de línea', type: 'text' },
  { key: 'letterSpacing', label: 'Espaciado de letras', type: 'text' },
  { key: 'textTransform', label: 'Transformación', type: 'select', options: ['none', 'uppercase', 'lowercase', 'capitalize'] },
  { key: 'textDecoration', label: 'Decoración', type: 'select', options: ['none', 'underline', 'line-through'] },
  { key: 'textAlign', label: 'Alineación', type: 'select', options: ['left', 'center', 'right', 'justify'] },
  { key: 'borderColor', label: 'Color del borde', type: 'color' },
  { key: 'borderStyle', label: 'Estilo del borde', type: 'select', options: ['none', 'solid', 'dashed', 'dotted', 'double'] },
  { key: 'borderWidth', label: 'Grosor del borde', type: 'text' },
  { key: 'borderRadius', label: 'Radio / Shape', type: 'text' },
  { key: 'boxShadow', label: 'Sombra', type: 'text' },
  { key: 'padding', label: 'Padding', type: 'text' },
  { key: 'paddingTop', label: 'Padding superior', type: 'text' },
  { key: 'paddingRight', label: 'Padding derecho', type: 'text' },
  { key: 'paddingBottom', label: 'Padding inferior', type: 'text' },
  { key: 'paddingLeft', label: 'Padding izquierdo', type: 'text' },
  { key: 'margin', label: 'Margin', type: 'text' },
  { key: 'marginTop', label: 'Margin superior', type: 'text' },
  { key: 'marginRight', label: 'Margin derecho', type: 'text' },
  { key: 'marginBottom', label: 'Margin inferior', type: 'text' },
  { key: 'marginLeft', label: 'Margin izquierdo', type: 'text' },
  { key: 'width', label: 'Ancho', type: 'text' },
  { key: 'minWidth', label: 'Ancho mínimo', type: 'text' },
  { key: 'maxWidth', label: 'Ancho máximo', type: 'text' },
  { key: 'height', label: 'Alto', type: 'text' },
  { key: 'minHeight', label: 'Alto mínimo', type: 'text' },
  { key: 'maxHeight', label: 'Alto máximo', type: 'text' },
  { key: 'opacity', label: 'Opacidad', type: 'text' },
  { key: 'display', label: 'Display', type: 'select', options: ['block', 'inline', 'inline-block', 'flex', 'inline-flex', 'grid', 'none'] },
  { key: 'position', label: 'Posición', type: 'select', options: ['static', 'relative', 'absolute', 'sticky'] },
  { key: 'top', label: 'Top', type: 'text' },
  { key: 'right', label: 'Right', type: 'text' },
  { key: 'bottom', label: 'Bottom', type: 'text' },
  { key: 'left', label: 'Left', type: 'text' },
  { key: 'zIndex', label: 'Z-index', type: 'text' },
  { key: 'flexDirection', label: 'Dirección', type: 'select', options: ['row', 'row-reverse', 'column', 'column-reverse'] },
  { key: 'justifyContent', label: 'Justificación', type: 'select', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'] },
  { key: 'alignItems', label: 'Alineación vertical', type: 'select', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'] },
  { key: 'gap', label: 'Gap', type: 'text' },
  { key: 'rowGap', label: 'Gap filas', type: 'text' },
  { key: 'columnGap', label: 'Gap columnas', type: 'text' },
  { key: 'gridTemplateColumns', label: 'Columnas de grid', type: 'text' },
  { key: 'overflow', label: 'Overflow', type: 'select', options: ['visible', 'hidden', 'auto', 'scroll'] },
  { key: 'cursor', label: 'Cursor', type: 'select', options: ['default', 'pointer', 'text', 'not-allowed', 'grab'] },
  { key: 'objectFit', label: 'Ajuste de imagen', type: 'select', options: ['contain', 'cover', 'fill', 'none'] },
  { key: 'transform', label: 'Transformación', type: 'text' },
  { key: 'transition', label: 'Transición', type: 'text' },
  { key: 'filter', label: 'Filtro', type: 'text' },
  { key: 'backdropFilter', label: 'Backdrop filter', type: 'text' },
  { key: 'outline', label: 'Outline', type: 'text' },
  { key: 'outlineOffset', label: 'Offset del outline', type: 'text' },
];

const BUTTON_PRESETS: Array<{ id: string; label: string; description: string; style: VisualElementStyle }> = [
  { id: 'solid', label: 'Sólido', description: 'Relleno clásico', style: { backgroundColor: '#16A36A', color: '#FFFFFF', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 8px 24px rgba(15, 23, 42, 0.10)' } },
  { id: 'soft', label: 'Suave', description: 'Relleno ligero', style: { backgroundColor: '#E8F7F0', color: '#11613F', borderColor: '#E8F7F0', borderStyle: 'solid', borderWidth: '1px', boxShadow: 'none' } },
  { id: 'outline', label: 'Outline', description: 'Solo contorno', style: { backgroundColor: '#FFFFFF', color: '#16A36A', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: 'none' } },
  { id: 'ghost', label: 'Ghost', description: 'Transparente', style: { backgroundColor: '#FFFFFF', color: '#0F172A', borderColor: '#E2E8F0', borderStyle: 'solid', borderWidth: '1px', boxShadow: 'none' } },
  { id: 'glass', label: 'Liquid Glass', description: 'Cristal translúcido', style: { backgroundColor: '#FFFFFF', color: '#0F172A', borderColor: '#E2E8F0', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 18px 45px rgba(15, 23, 42, 0.16)', backdropFilter: 'blur(12px)' } },
  { id: 'elevated', label: 'Elevado', description: 'Volumen marcado', style: { backgroundColor: '#FFFFFF', color: '#0F172A', borderColor: '#E2E8F0', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 18px 45px rgba(15, 23, 42, 0.16)' } },
  { id: 'flat', label: 'Plano', description: 'Sin sombra', style: { backgroundColor: '#16A36A', color: '#FFFFFF', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: 'none' } },
  { id: 'dark', label: 'Dark', description: 'Contraste oscuro', style: { backgroundColor: '#0F172A', color: '#FFFFFF', borderColor: '#0F172A', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 8px 24px rgba(15, 23, 42, 0.10)' } },
  { id: 'light', label: 'Light', description: 'Minimalista claro', style: { backgroundColor: '#FFFFFF', color: '#334155', borderColor: '#CBD5E1', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 2px 10px rgba(15, 23, 42, 0.06)' } },
  { id: 'success', label: 'Éxito', description: 'Acción positiva', style: { backgroundColor: '#16A36A', color: '#FFFFFF', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 8px 24px rgba(15, 23, 42, 0.10)' } },
  { id: 'warning', label: 'Advertencia', description: 'Atención', style: { backgroundColor: '#D97706', color: '#FFFFFF', borderColor: '#D97706', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 8px 24px rgba(15, 23, 42, 0.10)' } },
  { id: 'danger', label: 'Peligro', description: 'Acción destructiva', style: { backgroundColor: '#DC2626', color: '#FFFFFF', borderColor: '#DC2626', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 8px 24px rgba(15, 23, 42, 0.10)' } },
  { id: 'link', label: 'Link', description: 'Como enlace', style: { backgroundColor: '#FFFFFF', color: '#2563EB', borderColor: '#FFFFFF', borderStyle: 'none', borderWidth: '0px', boxShadow: 'none', padding: '0px' } },
  { id: 'compact', label: 'Compacto', description: 'Control pequeño', style: { backgroundColor: '#16A36A', color: '#FFFFFF', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: 'none', padding: '0.5rem 0.75rem' } },
  { id: 'large', label: 'Grande', description: 'CTA destacado', style: { backgroundColor: '#16A36A', color: '#FFFFFF', borderColor: '#16A36A', borderStyle: 'solid', borderWidth: '1px', boxShadow: '0 18px 45px rgba(15, 23, 42, 0.16)', padding: '1rem 1.5rem' } },
  { id: 'neumorphic', label: 'Soft UI', description: 'Volumen suave', style: { backgroundColor: '#F1F5F9', color: '#334155', borderColor: '#F1F5F9', borderStyle: 'solid', borderWidth: '1px', boxShadow: '8px 8px 18px rgba(15, 23, 42, 0.16)' } },
  { id: 'dashed', label: 'Dashed', description: 'Borde discontinuo', style: { backgroundColor: '#FFFFFF', color: '#334155', borderColor: '#94A3B8', borderStyle: 'dashed', borderWidth: '2px', boxShadow: 'none' } },
  { id: 'double', label: 'Double', description: 'Borde doble', style: { backgroundColor: '#FFFFFF', color: '#0F172A', borderColor: '#0F172A', borderStyle: 'double', borderWidth: '3px', boxShadow: 'none' } },
];
const SHAPES = [
  ['square', 'Cuadrado', '0px'], ['soft', 'Suave', '0.375rem'], ['rounded', 'Redondeado', '0.75rem'], ['curved', 'Curvo', '1rem'], ['pill', 'Píldora', '999px'], ['capsule', 'Cápsula', '2rem'], ['oval', 'Ovalado', '50%'], ['squircle', 'Squircle', '22%'], ['arch', 'Arco', '2rem 2rem 0.5rem 0.5rem'], ['reverse', 'Arco invertido', '0.5rem 0.5rem 2rem 2rem'], ['top', 'Curva superior', '1.5rem 1.5rem 0.25rem 0.25rem'], ['bottom', 'Curva inferior', '0.25rem 0.25rem 1.5rem 1.5rem'],
] as const;

function cssEscape(value: string) { try { return CSS.escape(value); } catch { return value.replace(/[^a-zA-Z0-9_-]/g, '\\$&'); } }
function isDynamicId(value: string) { return /^([0-9a-f]{8}-[0-9a-f-]{27,}|radix-|headlessui-|:r)/i.test(value) || /^\d+$/.test(value); }
function attrSelector(name: string, value: string) { return `[${name}="${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"]`; }
function selectorMatchesOnlyElement(selector: string, element: HTMLElement) { try { const matches = document.querySelectorAll<HTMLElement>(selector); return matches.length === 1 && matches[0] === element; } catch { return false; } }
function getNthOfType(element: HTMLElement) { if (!element.parentElement) return ''; const siblings = Array.from(element.parentElement.children).filter((child) => child.tagName === element.tagName); return siblings.length > 1 ? `:nth-of-type(${siblings.indexOf(element) + 1})` : ''; }
function buildFallbackSelector(element: HTMLElement) { const parts: string[] = []; let current: HTMLElement | null = element; while (current && current !== document.documentElement && current !== document.body) { parts.unshift(`${current.tagName.toLowerCase()}${getNthOfType(current)}`); const candidate = parts.join(' > '); if (selectorMatchesOnlyElement(candidate, element)) return candidate; current = current.parentElement; } return parts.join(' > '); }
function buildSelector(element: HTMLElement) {
  const parts: string[] = []; let current: HTMLElement | null = element;
  while (current && current !== document.documentElement && current !== document.body) {
    let part = current.tagName.toLowerCase(); const testId = current.getAttribute('data-testid'); const slot = current.getAttribute('data-slot'); const name = current.getAttribute('name'); const aria = current.getAttribute('aria-label'); const id = current.id;
    if (testId) part += attrSelector('data-testid', testId); else if (slot) part += attrSelector('data-slot', slot); else if (id && !isDynamicId(id)) part += `#${cssEscape(id)}`; else if (name) part += attrSelector('name', name); else if (aria) part += attrSelector('aria-label', aria); else part += getNthOfType(current);
    parts.unshift(part); const candidate = parts.join(' > '); if (selectorMatchesOnlyElement(candidate, element)) return candidate; current = current.parentElement;
  }
  return buildFallbackSelector(element);
}
function readVisibleText(element: HTMLElement) { const direct = Array.from(element.childNodes).filter((node): node is Text => node.nodeType === Node.TEXT_NODE && Boolean(node.textContent?.trim())); if (direct.length) return direct.map((node) => node.textContent?.trim() ?? '').join(' '); return element.childElementCount === 0 ? element.textContent?.trim() ?? '' : ''; }
function describeElement(element: HTMLElement) { const tag = element.tagName.toLowerCase(); const label = element.getAttribute('aria-label') || element.getAttribute('title') || readVisibleText(element).replace(/\s+/g, ' ').trim().slice(0, 70); const names: Record<string, string> = { button:'Botón',a:'Enlace',input:'Campo',select:'Selector',textarea:'Texto',img:'Imagen',nav:'Navegación',header:'Cabecera',section:'Sección',form:'Formulario',label:'Etiqueta',main:'Contenedor',aside:'Barra lateral',article:'Tarjeta',div:'Contenedor',span:'Texto',p:'Texto',h1:'Título',h2:'Título',h3:'Título',h4:'Título',h5:'Título',h6:'Título',li:'Elemento de lista',ul:'Lista',ol:'Lista',table:'Tabla',tr:'Fila',td:'Celda',th:'Celda' }; return `${names[tag] ?? 'Elemento'}${label ? ` — “${label}”` : ''}`; }
function toHex(value: string): string | undefined { const match = value.match(/^rgba?\((\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i); if (!match) return /^#[0-9a-f]{6}$/i.test(value) ? value : undefined; return `#${[1,2,3].map((index) => Number(match[index]).toString(16).padStart(2, '0')).join('')}`; }
function readComputedStyle(element: HTMLElement): VisualElementStyle { const s = window.getComputedStyle(element); return sanitizeVisualElementStyle({ textContent: readVisibleText(element), backgroundColor: toHex(s.backgroundColor), backgroundImage: /^linear-gradient\(/.test(s.backgroundImage) ? s.backgroundImage : undefined, color: toHex(s.color), borderColor: toHex(s.borderTopColor), borderStyle: s.borderTopStyle, borderWidth: s.borderTopWidth, borderRadius: s.borderRadius, boxShadow: s.boxShadow, fontFamily: s.fontFamily, fontSize: s.fontSize, fontWeight: s.fontWeight, lineHeight: s.lineHeight, letterSpacing: s.letterSpacing, textTransform: s.textTransform, textDecoration: s.textDecorationLine === 'none' ? 'none' : s.textDecorationLine.includes('line-through') ? 'line-through' : 'underline', textAlign: s.textAlign, padding: s.padding, paddingTop: s.paddingTop, paddingRight: s.paddingRight, paddingBottom: s.paddingBottom, paddingLeft: s.paddingLeft, margin: s.margin, marginTop: s.marginTop, marginRight: s.marginRight, marginBottom: s.marginBottom, marginLeft: s.marginLeft, width: s.width, minWidth: s.minWidth, maxWidth: s.maxWidth, height: s.height, minHeight: s.minHeight, maxHeight: s.maxHeight, opacity: s.opacity, display: s.display as VisualElementStyle['display'], position: s.position as VisualElementStyle['position'], top: s.top, right: s.right, bottom: s.bottom, left: s.left, zIndex: s.zIndex, flexDirection: s.flexDirection as VisualElementStyle['flexDirection'], justifyContent: s.justifyContent as VisualElementStyle['justifyContent'], alignItems: s.alignItems as VisualElementStyle['alignItems'], gap: s.gap, rowGap: s.rowGap, columnGap: s.columnGap, gridTemplateColumns: s.gridTemplateColumns, overflow: s.overflow as VisualElementStyle['overflow'], cursor: s.cursor as VisualElementStyle['cursor'], objectFit: s.objectFit as VisualElementStyle['objectFit'], transform: s.transform === 'none' ? 'none' : s.transform, transition: s.transition, filter: s.filter === 'none' ? 'none' : s.filter, backdropFilter: s.backdropFilter === 'none' ? 'none' : s.backdropFilter, outline: s.outline, outlineOffset: s.outlineOffset }); }
function cloneOverrides(source: VisualSettingsDraft['element_overrides']) { return Object.fromEntries(Object.entries(source ?? {}).map(([selector, style]) => [selector, { ...style }])); }
function getInitialOverrides(settings: ReturnType<typeof useVisualTheme>['settings'], scope: VisualInterfaceScope) { return cloneOverrides(settings.interface_overrides?.[scope]?.element_overrides ?? settings.element_overrides); }

function ButtonPresetGrid({ onApply }: { onApply: (style: VisualElementStyle) => void }) { return <div className="grid grid-cols-2 gap-2">{BUTTON_PRESETS.map((preset) => <button key={preset.id} type="button" onClick={() => onApply(preset.style)} className="group rounded-xl border border-slate-200 bg-white p-2 text-left transition hover:border-slate-400 hover:shadow-sm"><span className="flex h-9 items-center justify-center border text-[10px] font-black transition group-hover:scale-[1.01]" style={{ backgroundColor:preset.style.backgroundColor,color:preset.style.color,borderColor:preset.style.borderColor,borderStyle:preset.style.borderStyle,borderWidth:preset.style.borderWidth }}>{preset.label}</span><span className="mt-1 block text-[9px] text-slate-400">{preset.description}</span></button>)}</div>; }

export function VisualPreviewEditor({ scope }: Props) {
  const { settings } = useVisualTheme(); const [selected,setSelected] = useState<Selected>(null); const [draftStyle,setDraftStyle] = useState<VisualElementStyle>({}); const [inspectedStyle,setInspectedStyle] = useState<VisualElementStyle>({}); const [sessionOverrides,setSessionOverrides] = useState(() => getInitialOverrides(settings,scope)); const sessionOverridesRef=useRef(sessionOverrides); const [message,setMessage]=useState('1 clic ejecuta · 3 clics editan · Modo diseño selecciona directamente'); const [designMode,setDesignMode]=useState(false); const clickState=useRef<{element:HTMLElement|null;count:number;timer:number|null}>({element:null,count:0,timer:null}); const replayingClick=useRef(false); const [openSection,setOpenSection]=useState<'button'|'shape'|'typography'|'box'|'layout'|'effects'|'advanced'|null>('typography');
  const selectedStyle=useMemo(()=>selected?{...inspectedStyle,...(sessionOverrides[selected.selector]??{}),...draftStyle}:{},[draftStyle,inspectedStyle,selected,sessionOverrides]); const isButton=Boolean(selected && (/^(button|a)$/i.test(selected.tag) || selected.element.getAttribute('role')==='button'));
  const syncSessionOverrides=(next: VisualSettingsDraft['element_overrides'])=>{const cloned=cloneOverrides(next);sessionOverridesRef.current=cloned;setSessionOverrides(cloned);}; useEffect(()=>{sessionOverridesRef.current=sessionOverrides},[sessionOverrides]);
  const selectElement=(element:HTMLElement)=>{const selector=buildSelector(element);if(!selector||!selectorMatchesOnlyElement(selector,element)){setSelected(null);setMessage('No se pudo identificar este elemento de forma segura.');return;}setSelected({element,selector,label:describeElement(element),tag:element.tagName.toLowerCase()});setInspectedStyle(readComputedStyle(element));setDraftStyle({...sessionOverridesRef.current[selector]??{}});setOpenSection(/^(button|a)$/i.test(element.tagName)||element.getAttribute('role')==='button'?'button':'typography');};
  useEffect(()=>{const onPreviewMessage=(event:MessageEvent)=>{if(event.origin!==window.location.origin||event.data?.type!=='quickbite-visual-preview'||!event.data?.settings)return;const next=sanitizeVisualSettings(event.data.settings as Partial<VisualSettingsDraft>);const incoming=next.element_overrides??{};syncSessionOverrides(incoming);if(selected)setDraftStyle({...incoming[selected.selector]??{}})};window.addEventListener('message',onPreviewMessage);return()=>window.removeEventListener('message',onPreviewMessage)},[selected]);
  useEffect(()=>{const handleSelection=(event:MouseEvent)=>{const target=event.target;if(!(target instanceof HTMLElement)||replayingClick.current||target.closest(PROTECTED_SELECTOR))return;if(event.metaKey||event.ctrlKey||event.altKey||event.shiftKey)return;const editable=target.closest('*') as HTMLElement|null;if(!editable||editable===document.body||editable===document.documentElement||/^(script|style|link|meta|noscript)$/i.test(editable.tagName))return;const state=clickState.current;state.count=state.element===editable?state.count+1:1;state.element=editable;if(state.timer)window.clearTimeout(state.timer);if(designMode){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();selectElement(editable);setMessage('Modo diseño: elemento seleccionado. Todo lo visual es editable.');state.element=null;state.count=0;state.timer=null;return;}event.preventDefault();event.stopPropagation();if(state.count>=3){state.count=0;state.timer=null;event.stopImmediatePropagation();selectElement(editable);setMessage('Elemento seleccionado: puedes modificarlo por completo.');return;}state.timer=window.setTimeout(()=>{const current=clickState.current;if(current.element!==editable||current.count<1)return;replayingClick.current=true;try{editable.click()}finally{window.setTimeout(()=>{replayingClick.current=false},0)}current.element=null;current.count=0;current.timer=null},CLICK_DELAY)};document.addEventListener('click',handleSelection,true);return()=>{document.removeEventListener('click',handleSelection,true);if(clickState.current.timer)window.clearTimeout(clickState.current.timer)}},[designMode]);
  useEffect(()=>{if(!selected)return;const element=selected.element;const previous=new Map<string,string>();Object.entries(draftStyle).forEach(([key,value])=>{if(!value||key==='textContent')return;const property=key.replace(/[A-Z]/g,(letter)=>`-${letter.toLowerCase()}`);previous.set(property,element.style.getPropertyValue(property));element.style.setProperty(property,value,'important')});return()=>previous.forEach((value,property)=>value?element.style.setProperty(property,value):element.style.removeProperty(property))},[draftStyle,selected]);
  const buildDraftSettings=(nextOverrides:Record<string,VisualElementStyle>)=>{const currentScope=settings.interface_overrides?.[scope]??{};return sanitizeVisualSettings({...settings,element_overrides:nextOverrides,interface_overrides:{...(settings.interface_overrides??{}),[scope]:{...currentScope,element_overrides:nextOverrides}}})};
  const notifyHost=(type:'quickbite-visual-element-edit'|'quickbite-visual-element-reset',fullSettings:VisualSettingsDraft,selector:string,styles?:VisualElementStyle)=>{try{window.parent!==window?window.parent.postMessage({type,scope,selector,...(styles?{styles}:{}),settings:fullSettings},window.location.origin):window.opener?.postMessage({type,scope,selector,...(styles?{styles}:{}),settings:fullSettings},window.location.origin)}catch{/* optional host */}};
  const commit=(patch:VisualElementStyle)=>{if(!selected)return;const current=sessionOverridesRef.current[selected.selector]??{};const next=sanitizeVisualElementStyle({...current,...draftStyle,...patch});const nextOverrides={...sessionOverridesRef.current,[selected.selector]:next};syncSessionOverrides(nextOverrides);setDraftStyle(next);notifyHost('quickbite-visual-element-edit',buildDraftSettings(nextOverrides),selected.selector,next);setMessage('Cambio aplicado al borrador. Sigue editando sin salir de la preview.');};
  const reset=()=>{if(!selected)return;const next={...sessionOverridesRef.current};delete next[selected.selector];syncSessionOverrides(next);setDraftStyle({});setInspectedStyle(readComputedStyle(selected.element));notifyHost('quickbite-visual-element-reset',buildDraftSettings(next),selected.selector);setMessage('Elemento restaurado al estilo original.');}; const closeEditor=()=>{setSelected(null);setMessage(designMode?'Modo diseño: selecciona cualquier elemento.':'1 clic ejecuta · 3 clics editan · Modo diseño selecciona directamente');};
  const Section=({id,title,children}:{id:NonNullable<typeof openSection>;title:string;children:React.ReactNode})=><div className="overflow-hidden rounded-2xl border border-slate-200"><button type="button" onClick={()=>setOpenSection(openSection===id?null:id)} className="flex w-full items-center justify-between bg-slate-50 px-4 py-3 text-left"><span className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-700">{title}</span><ChevronDown className={`size-4 text-slate-400 transition ${openSection===id?'rotate-180':''}`}/></button>{openSection===id&&<div className="p-4">{children}</div>}</div>;
  const FieldEditor=({field}:{field:Field})=>{const value=selectedStyle[field.key]??'';const stringValue=String(value);return <label className="block"><span className="mb-1 block text-xs font-black text-slate-600">{field.label}</span>{field.type==='color'&&<div className="flex gap-2"><input type="color" value={typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value:'#ffffff'} onChange={e=>commit({[field.key]:e.target.value} as VisualElementStyle)} className="size-10 cursor-pointer rounded-lg border border-slate-200 p-1"/><input value={stringValue} onChange={e=>commit({[field.key]:e.target.value} as VisualElementStyle)} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm"/></div>}{field.type==='select'&&<select value={stringValue} onChange={e=>commit({[field.key]:e.target.value} as VisualElementStyle)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm">{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select>}{field.type==='textarea'&&<textarea value={stringValue} onChange={e=>commit({[field.key]:e.target.value} as VisualElementStyle)} className="min-h-20 w-full resize-y rounded-xl border border-slate-200 px-3 py-2 text-sm" placeholder="Texto visible" maxLength={500}/>} {field.type==='text'&&<input value={stringValue} onChange={e=>commit({[field.key]:e.target.value} as VisualElementStyle)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" placeholder="Auto"/>}</label>};
  return <>
    <div data-qb-visual-editor className="fixed left-4 top-4 z-[9998] flex max-w-[calc(100vw-2rem)] items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/90 px-4 py-3 text-white shadow-2xl backdrop-blur-xl"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-white/10"><Edit3 className="size-4"/></div><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-300">Editor visual universal</p><p className="truncate text-xs font-bold">{message}</p></div><button type="button" onClick={()=>setDesignMode(v=>!v)} className={`shrink-0 rounded-xl px-3 py-2 text-[10px] font-black ${designMode?'bg-white text-slate-900':'bg-white/10 text-white hover:bg-white/15'}`}>{designMode?'Modo diseño':'Interactivo'}</button></div>
    {selected&&<aside data-qb-visual-editor-panel className="fixed bottom-4 right-4 z-[9999] w-[min(480px,calc(100vw-2rem))] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-start justify-between gap-3 border-b border-slate-200 px-5 py-4"><div className="min-w-0"><div className="flex items-center gap-2"><Sparkles className="size-4 text-emerald-600"/><p className="text-xs font-black uppercase tracking-[.16em] text-slate-500">Personalizar elemento</p></div><p className="mt-1 truncate text-sm font-black text-slate-900">{selected.label}</p><p className="mt-1 truncate text-[10px] text-slate-400">{selected.selector}</p><p className="mt-2 text-[10px] font-semibold text-slate-500">Todo lo visual queda en el borrador hasta Guardar.</p></div><button type="button" onClick={closeEditor} className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600 hover:bg-slate-200"><X className="size-4"/></button></div>
      <div className="max-h-[76vh] space-y-3 overflow-y-auto p-4">
        {isButton&&<Section id="button" title="Tipo de botón"><p className="mb-3 text-[10px] leading-4 text-slate-500">18 estilos base. Después puedes cambiar absolutamente cada propiedad.</p><ButtonPresetGrid onApply={commit}/></Section>}
        {isButton&&<Section id="shape" title="Shape / forma"><div className="grid grid-cols-3 gap-2">{SHAPES.map(([id,label,value])=><button key={id} type="button" onClick={()=>commit({borderRadius:value})} className="rounded-xl border border-slate-200 bg-white p-2 text-center hover:border-slate-400"><span className="mx-auto block h-8 w-16 border border-slate-300 bg-slate-100" style={{borderRadius:value}}/><span className="mt-1 block text-[9px] font-black text-slate-600">{label}</span></button>)}</div></Section>}
        <Section id="typography" title="Texto y tipografía"><div className="space-y-3">{FIELDS.filter(f=>['textContent','color','fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','textTransform','textDecoration','textAlign'].includes(f.key)).map(f=><FieldEditor key={String(f.key)} field={f}/>)}</div></Section>
        <Section id="box" title="Colores, borde y espacio"><div className="space-y-3">{FIELDS.filter(f=>['backgroundColor','backgroundImage','borderColor','borderStyle','borderWidth','borderRadius','boxShadow','padding','paddingTop','paddingRight','paddingBottom','paddingLeft','margin','marginTop','marginRight','marginBottom','marginLeft'].includes(f.key)).map(f=><FieldEditor key={String(f.key)} field={f}/>)}</div></Section>
        <Section id="layout" title="Tamaño y layout"><div className="space-y-3">{FIELDS.filter(f=>['width','minWidth','maxWidth','height','minHeight','maxHeight','display','position','top','right','bottom','left','zIndex','flexDirection','justifyContent','alignItems','gap','rowGap','columnGap','gridTemplateColumns','overflow','objectFit'].includes(f.key)).map(f=><FieldEditor key={String(f.key)} field={f}/>)}</div></Section>
        <Section id="effects" title="Efectos e interacción"><div className="space-y-3">{FIELDS.filter(f=>['opacity','cursor','transform','transition','filter','backdropFilter','outline','outlineOffset'].includes(f.key)).map(f=><FieldEditor key={String(f.key)} field={f}/>)}</div></Section>
        <Section id="advanced" title="Acciones"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={reset} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-black text-slate-700"><RotateCcw className="size-4"/>Restablecer</button><button type="button" onClick={closeEditor} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-3 py-2.5 text-xs font-black text-white"><Check className="size-4"/>Listo</button></div><p className="mt-3 text-[9px] leading-4 text-slate-400">El editor solo modifica presentación. No altera lógica, permisos, pagos, pedidos ni datos.</p></Section>
      </div></aside>}
  </>;
}
