-- Automatic daily operational summaries.
CREATE OR REPLACE FUNCTION public.refresh_daily_summary(p_business_date DATE) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_orders_count INTEGER; v_delivered_orders_count INTEGER; v_sales_total NUMERIC(12,2); v_items_sold INTEGER; v_average_ticket NUMERIC(12,2); v_top_product_id UUID; v_low_product_id UUID; v_critical_stock_count INTEGER; BEGIN SELECT COUNT(*)::INTEGER, COUNT(*) FILTER (WHERE status = 'delivered')::INTEGER, COALESCE(SUM(total) FILTER (WHERE payment_status = 'confirmed' AND status <> 'cancelled'), 0)::NUMERIC(12,2), COALESCE(AVG(total) FILTER (WHERE payment_status = 'confirmed' AND status <> 'cancelled'), 0)::NUMERIC(12,2) INTO v_orders_count, v_delivered_orders_count, v_sales_total, v_average_ticket FROM public.orders WHERE created_at::date = p_business_date AND COALESCE(admin_hidden, false) = false; SELECT COALESCE(SUM(oi.quantity), 0)::INTEGER INTO v_items_sold FROM public.order_items oi JOIN public.orders o ON o.id = oi.order_id WHERE o.created_at::date = p_business_date AND o.payment_status = 'confirmed' AND o.status <> 'cancelled' AND COALESCE(o.admin_hidden, false) = false; SELECT oi.product_id INTO v_top_product_id FROM public.order_items oi JOIN public.orders o ON o.id = oi.order_id WHERE o.created_at::date = p_business_date AND o.payment_status = 'confirmed' AND o.status <> 'cancelled' AND COALESCE(o.admin_hidden, false) = false GROUP BY oi.product_id ORDER BY SUM(oi.quantity) DESC, oi.product_id LIMIT 1; SELECT p.id INTO v_low_product_id FROM public.products p WHERE p.available = true ORDER BY p.stock ASC, p.name ASC LIMIT 1; SELECT COUNT(*)::INTEGER INTO v_critical_stock_count FROM public.products p JOIN public.product_stock_settings s ON s.product_id = p.id WHERE p.stock <= s.minimum_stock; INSERT INTO public.daily_summaries (business_date, orders_count, delivered_orders_count, sales_total, items_sold, average_ticket, top_product_id, low_product_id, critical_stock_count, generated_at) VALUES (p_business_date, v_orders_count, v_delivered_orders_count, v_sales_total, v_items_sold, v_average_ticket, v_top_product_id, v_low_product_id, v_critical_stock_count, NOW()) ON CONFLICT (business_date) DO UPDATE SET orders_count = EXCLUDED.orders_count, delivered_orders_count = EXCLUDED.delivered_orders_count, sales_total = EXCLUDED.sales_total, items_sold = EXCLUDED.items_sold, average_ticket = EXCLUDED.average_ticket, top_product_id = EXCLUDED.top_product_id, low_product_id = EXCLUDED.low_product_id, critical_stock_count = EXCLUDED.critical_stock_count, generated_at = EXCLUDED.generated_at; END; $$;
REVOKE ALL ON FUNCTION public.refresh_daily_summary(DATE) FROM PUBLIC;
CREATE OR REPLACE FUNCTION public.refresh_daily_summary_from_order() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN PERFORM public.refresh_daily_summary(NEW.created_at::date); IF TG_OP = 'UPDATE' AND OLD.created_at::date <> NEW.created_at::date THEN PERFORM public.refresh_daily_summary(OLD.created_at::date); END IF; RETURN NEW; END; $$;
REVOKE ALL ON FUNCTION public.refresh_daily_summary_from_order() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_refresh_daily_summary_order ON public.orders;
CREATE TRIGGER trg_refresh_daily_summary_order AFTER INSERT OR UPDATE OF status, payment_status, total, created_at, admin_hidden ON public.orders FOR EACH ROW EXECUTE FUNCTION public.refresh_daily_summary_from_order();
CREATE OR REPLACE FUNCTION public.refresh_daily_summary_from_item() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_business_date DATE; BEGIN SELECT created_at::date INTO v_business_date FROM public.orders WHERE id = NEW.order_id; IF v_business_date IS NOT NULL THEN PERFORM public.refresh_daily_summary(v_business_date); END IF; RETURN NEW; END; $$;
REVOKE ALL ON FUNCTION public.refresh_daily_summary_from_item() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_refresh_daily_summary_item ON public.order_items;
CREATE TRIGGER trg_refresh_daily_summary_item AFTER INSERT OR UPDATE OF quantity, price, order_id ON public.order_items FOR EACH ROW EXECUTE FUNCTION public.refresh_daily_summary_from_item();
DO $$ DECLARE d DATE; BEGIN FOR d IN SELECT generate_series(CURRENT_DATE - 14, CURRENT_DATE, INTERVAL '1 day')::date LOOP PERFORM public.refresh_daily_summary(d); END LOOP; END $$;
