-- QuickBite resilience baseline.
--
-- This migration deliberately keeps the existing application schema and UI
-- contracts intact. It adds an append-only operational audit, health-check
-- storage, secure RPCs and an idempotency key for orders.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.system_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_user_id UUID,
  action TEXT NOT NULL CHECK (length(trim(action)) BETWEEN 3 AND 120),
  module TEXT NOT NULL CHECK (length(trim(module)) BETWEEN 2 AND 80),
  operation TEXT NOT NULL CHECK (length(trim(operation)) BETWEEN 2 AND 80),
  entity_type TEXT,
  entity_id TEXT,
  status TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'failure')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object')
);

-- These first audit tables were created before this repository received their
-- migration. Extend that compatible shape rather than replacing it.
ALTER TABLE public.system_audit_logs
  ADD COLUMN IF NOT EXISTS module TEXT,
  ADD COLUMN IF NOT EXISTS operation TEXT;

UPDATE public.system_audit_logs
SET module = COALESCE(NULLIF(split_part(action, '.', 1), ''), 'system'),
    operation = COALESCE(NULLIF(split_part(action, '.', 2), ''), 'event')
WHERE module IS NULL OR operation IS NULL;

ALTER TABLE public.system_audit_logs
  ALTER COLUMN module SET NOT NULL,
  ALTER COLUMN operation SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_system_audit_logs_created_at
  ON public.system_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_audit_logs_actor_created_at
  ON public.system_audit_logs (actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_audit_logs_module_created_at
  ON public.system_audit_logs (module, created_at DESC);

CREATE TABLE IF NOT EXISTS public.system_health_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL CHECK (length(trim(service)) BETWEEN 2 AND 80),
  status TEXT NOT NULL CHECK (status IN ('healthy', 'degraded', 'unhealthy')),
  latency_ms INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
  checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  details JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_system_health_checks_service_checked_at
  ON public.system_health_checks (service, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_health_checks_status_checked_at
  ON public.system_health_checks (status, checked_at DESC);

-- Never allow an audit payload to become a secondary place for credentials.
-- The check is recursive so nested objects and arrays are covered too.
CREATE OR REPLACE FUNCTION public.audit_payload_has_sensitive_key(p_payload JSONB)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
SET search_path = pg_catalog
AS $$
DECLARE
  v_key TEXT;
  v_value JSONB;
BEGIN
  IF p_payload IS NULL OR p_payload IN ('null'::jsonb, '{}'::jsonb, '[]'::jsonb) THEN
    RETURN false;
  END IF;

  CASE jsonb_typeof(p_payload)
    WHEN 'object' THEN
      FOR v_key, v_value IN SELECT key, value FROM jsonb_each(p_payload)
      LOOP
        IF lower(v_key) ~ '(password|passphrase|secret|token|authorization|cookie|api[_-]?key|private[_-]?key|jwt|credential)' THEN
          RETURN true;
        END IF;
        IF public.audit_payload_has_sensitive_key(v_value) THEN
          RETURN true;
        END IF;
      END LOOP;
    WHEN 'array' THEN
      FOR v_value IN SELECT value FROM jsonb_array_elements(p_payload) AS values_table(value)
      LOOP
        IF public.audit_payload_has_sensitive_key(v_value) THEN
          RETURN true;
        END IF;
      END LOOP;
  END CASE;

  RETURN false;
END;
$$;

REVOKE ALL ON FUNCTION public.audit_payload_has_sensitive_key(JSONB) FROM PUBLIC;

-- Internal writer used by database triggers and the authenticated RPC below.
CREATE OR REPLACE FUNCTION public.record_system_audit(
  p_actor_id UUID,
  p_action TEXT,
  p_module TEXT,
  p_operation TEXT,
  p_entity_type TEXT DEFAULT NULL,
  p_entity_id TEXT DEFAULT NULL,
  p_status TEXT DEFAULT 'success',
  p_details JSONB DEFAULT '{}'::jsonb
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_id UUID;
BEGIN
  IF trim(COALESCE(p_action, '')) = ''
    OR trim(COALESCE(p_module, '')) = ''
    OR trim(COALESCE(p_operation, '')) = '' THEN
    RAISE EXCEPTION 'invalid_audit_event';
  END IF;

  IF p_status NOT IN ('success', 'failure') THEN
    RAISE EXCEPTION 'invalid_audit_status';
  END IF;

  IF jsonb_typeof(COALESCE(p_details, '{}'::jsonb)) <> 'object'
    OR public.audit_payload_has_sensitive_key(COALESCE(p_details, '{}'::jsonb)) THEN
    RAISE EXCEPTION 'sensitive_audit_metadata';
  END IF;

  INSERT INTO public.system_audit_logs (
    actor_user_id, action, module, operation, entity_type, entity_id, status, metadata
  ) VALUES (
    p_actor_id,
    left(trim(p_action), 120),
    left(trim(p_module), 80),
    left(trim(p_operation), 80),
    NULLIF(left(trim(COALESCE(p_entity_type, '')), 80), ''),
    NULLIF(left(trim(COALESCE(p_entity_id, '')), 160), ''),
    p_status,
    COALESCE(p_details, '{}'::jsonb)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.record_system_audit(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC, anon, authenticated;

-- Browser code may record only its own successful/failed actions. The actor
-- is always derived from the JWT, never trusted from a submitted payload.
CREATE OR REPLACE FUNCTION public.write_system_audit_event(
  p_action TEXT,
  p_entity_type TEXT DEFAULT NULL,
  p_entity_id TEXT DEFAULT NULL,
  p_details JSONB DEFAULT '{}'::jsonb,
  p_status TEXT DEFAULT 'success'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, auth
AS $$
DECLARE
  v_action TEXT := lower(trim(COALESCE(p_action, '')));
  v_module TEXT;
  v_operation TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  IF v_action !~ '^[a-z][a-z0-9_]{1,79}\.[a-z][a-z0-9_]{1,79}$' THEN
    RAISE EXCEPTION 'invalid_audit_action';
  END IF;

  v_module := split_part(v_action, '.', 1);
  v_operation := split_part(v_action, '.', 2);
  RETURN public.record_system_audit(
    auth.uid(), v_action, v_module, v_operation,
    p_entity_type, p_entity_id, p_status, COALESCE(p_details, '{}'::jsonb)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.write_system_audit_event(TEXT, TEXT, TEXT, JSONB, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.write_system_audit_event(TEXT, TEXT, TEXT, JSONB, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.audit_business_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, auth
AS $$
DECLARE
  v_actor_id UUID := auth.uid();
  v_action TEXT;
  v_module TEXT;
  v_operation TEXT;
  v_entity_type TEXT := TG_TABLE_NAME;
  v_entity_id TEXT;
  v_details JSONB;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_entity_id := OLD.id::text;
  ELSE
    v_entity_id := NEW.id::text;
  END IF;

  IF TG_TABLE_NAME = 'products' THEN
    IF TG_OP = 'INSERT' THEN
      v_action := 'product.create';
      v_module := 'catalog';
      v_operation := 'create';
      v_details := jsonb_build_object('name', NEW.name, 'stock', NEW.stock, 'available', NEW.available);
    ELSIF TG_OP = 'DELETE' THEN
      v_action := 'product.delete';
      v_module := 'catalog';
      v_operation := 'delete';
      v_details := jsonb_build_object('name', OLD.name, 'stock', OLD.stock);
    ELSIF OLD.stock IS DISTINCT FROM NEW.stock THEN
      v_action := 'inventory.update';
      v_module := 'inventory';
      v_operation := 'adjust';
      v_details := jsonb_build_object(
        'product_name', NEW.name,
        'previous_stock', OLD.stock,
        'stock', NEW.stock,
        'delta', NEW.stock - OLD.stock
      );
    ELSE
      v_action := 'product.update';
      v_module := 'catalog';
      v_operation := 'update';
      v_details := jsonb_build_object('name', NEW.name, 'price', NEW.price, 'available', NEW.available);
    END IF;
  ELSIF TG_TABLE_NAME = 'categories' THEN
    v_action := 'category.' || lower(TG_OP);
    v_module := 'catalog';
    v_operation := lower(TG_OP);
    IF TG_OP = 'DELETE' THEN
      v_details := jsonb_build_object('name', OLD.name);
    ELSE
      v_details := jsonb_build_object('name', NEW.name);
    END IF;
  ELSIF TG_TABLE_NAME = 'orders' THEN
    IF TG_OP = 'INSERT' THEN
      v_action := 'order.create';
      v_module := 'orders';
      v_operation := 'create';
      v_details := jsonb_build_object(
        'order_number', NEW.order_number,
        'total', NEW.total,
        'status', NEW.status,
        'payment_status', NEW.payment_status,
        'payment_method', NEW.payment_method
      );
    ELSIF TG_OP = 'DELETE' THEN
      v_action := 'order.delete';
      v_module := 'orders';
      v_operation := 'delete';
      v_details := jsonb_build_object('order_number', OLD.order_number, 'total', OLD.total);
    ELSIF OLD.status IS DISTINCT FROM NEW.status THEN
      v_action := 'order.status_change';
      v_module := 'orders';
      v_operation := 'status_change';
      v_details := jsonb_build_object('order_number', NEW.order_number, 'from', OLD.status, 'to', NEW.status);
    ELSIF OLD.payment_status IS DISTINCT FROM NEW.payment_status THEN
      v_action := 'payment.update';
      v_module := 'payments';
      v_operation := 'status_change';
      v_details := jsonb_build_object('order_number', NEW.order_number, 'from', OLD.payment_status, 'to', NEW.payment_status);
    ELSIF OLD.admin_hidden IS DISTINCT FROM NEW.admin_hidden THEN
      v_action := 'order.archive';
      v_module := 'sales';
      v_operation := CASE WHEN NEW.admin_hidden THEN 'close_period' ELSE 'restore_period' END;
      v_details := jsonb_build_object('order_number', NEW.order_number, 'hidden', NEW.admin_hidden);
    ELSE
      v_action := 'order.update';
      v_module := 'orders';
      v_operation := 'update';
      v_details := jsonb_build_object('order_number', NEW.order_number);
    END IF;
  ELSIF TG_TABLE_NAME = 'profiles' THEN
    v_action := 'user.' || lower(TG_OP);
    v_module := 'users';
    v_operation := lower(TG_OP);
    IF TG_OP = 'DELETE' THEN
      v_details := jsonb_build_object('role', OLD.role);
    ELSE
      v_details := jsonb_build_object('role', NEW.role);
    END IF;
  ELSE
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  PERFORM public.record_system_audit(
    v_actor_id, v_action, v_module, v_operation, v_entity_type, v_entity_id, 'success', v_details
  );
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_products_change ON public.products;
CREATE TRIGGER audit_products_change
AFTER INSERT OR UPDATE OR DELETE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.audit_business_change();

DROP TRIGGER IF EXISTS audit_categories_change ON public.categories;
CREATE TRIGGER audit_categories_change
AFTER INSERT OR UPDATE OR DELETE ON public.categories
FOR EACH ROW EXECUTE FUNCTION public.audit_business_change();

DROP TRIGGER IF EXISTS audit_orders_change ON public.orders;
CREATE TRIGGER audit_orders_change
AFTER INSERT OR UPDATE OR DELETE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.audit_business_change();

DROP TRIGGER IF EXISTS audit_profiles_change ON public.profiles;
CREATE TRIGGER audit_profiles_change
AFTER INSERT OR UPDATE OR DELETE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.audit_business_change();

-- Direct browser insertion into the old audit table is retired. Its existing
-- records are retained; new records use the filtered system audit RPC above.
DROP POLICY IF EXISTS audit_logs_insert_authenticated ON public.audit_logs;

ALTER TABLE public.system_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_health_checks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.system_audit_logs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.system_health_checks FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.system_audit_logs TO service_role;
GRANT ALL ON TABLE public.system_health_checks TO service_role;

DROP POLICY IF EXISTS system_audit_logs_select_admin ON public.system_audit_logs;
CREATE POLICY system_audit_logs_select_admin
  ON public.system_audit_logs FOR SELECT TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS system_health_checks_select_admin ON public.system_health_checks;
CREATE POLICY system_health_checks_select_admin
  ON public.system_health_checks FOR SELECT TO authenticated
  USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.record_system_health_check(
  p_service TEXT,
  p_status TEXT,
  p_latency_ms INTEGER DEFAULT NULL,
  p_details JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_id BIGINT;
  v_service TEXT := lower(trim(COALESCE(p_service, '')));
BEGIN
  IF v_service = '' OR p_status NOT IN ('healthy', 'degraded', 'unhealthy') THEN
    RAISE EXCEPTION 'invalid_health_check';
  END IF;
  IF p_latency_ms IS NOT NULL AND p_latency_ms < 0 THEN
    RAISE EXCEPTION 'invalid_health_latency';
  END IF;
  IF jsonb_typeof(COALESCE(p_details, '{}'::jsonb)) <> 'object'
    OR public.audit_payload_has_sensitive_key(COALESCE(p_details, '{}'::jsonb)) THEN
    RAISE EXCEPTION 'sensitive_health_metadata';
  END IF;

  -- A public health endpoint can be probed frequently. Store at most one
  -- identical result per service/status per minute, while still recording
  -- transitions immediately.
  SELECT id INTO v_id
  FROM public.system_health_checks
  WHERE service = v_service
    AND status = p_status
    AND checked_at >= NOW() - INTERVAL '1 minute'
  ORDER BY checked_at DESC
  LIMIT 1;

  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  INSERT INTO public.system_health_checks (service, status, latency_ms, details)
  VALUES (v_service, p_status, p_latency_ms, COALESCE(p_details, '{}'::jsonb))
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.record_system_health_check(TEXT, TEXT, INTEGER, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_system_health_check(TEXT, TEXT, INTEGER, JSONB) TO service_role;

CREATE OR REPLACE FUNCTION public.get_system_health_summary()
RETURNS TABLE(
  service TEXT,
  status TEXT,
  latency_ms INTEGER,
  checked_at TIMESTAMPTZ,
  details JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;

  RETURN QUERY
  SELECT DISTINCT ON (health.service)
    health.service,
    health.status,
    health.latency_ms,
    health.checked_at,
    health.details
  FROM public.system_health_checks AS health
  ORDER BY health.service, health.checked_at DESC;
END;
$$;

REVOKE ALL ON FUNCTION public.get_system_health_summary() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_system_health_summary() TO authenticated;

-- A client request id makes the order RPC safe to retry after a transient
-- network timeout. Existing rows keep NULL and remain valid.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS client_request_id UUID;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_client_request_id_key'
      AND conrelid = 'public.orders'::regclass
  ) THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_client_request_id_key UNIQUE (client_request_id);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_order_tx(
  p_user_id UUID,
  p_payment_method TEXT,
  p_payment_status TEXT,
  p_status TEXT,
  p_pickup_code TEXT,
  p_estimated_minutes INTEGER,
  p_payment_reference TEXT,
  p_items JSONB,
  p_request_id UUID
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, auth
AS $$
DECLARE
  v_order_id UUID := gen_random_uuid();
  v_order_number TEXT := 'QB' || to_char(NOW(), 'YYMMDD') || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  v_total NUMERIC(10,2) := 0;
  v_item JSONB;
  v_product RECORD;
  v_quantity INTEGER;
  v_existing_order_number TEXT;
BEGIN
  IF auth.uid() IS NULL OR (auth.uid() <> p_user_id AND NOT public.is_admin()) THEN
    RAISE EXCEPTION 'not_authorized';
  END IF;
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION 'order_request_id_required';
  END IF;
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'order_items_required';
  END IF;

  SELECT order_number INTO v_existing_order_number
  FROM public.orders
  WHERE client_request_id = p_request_id
    AND user_id = p_user_id;
  IF v_existing_order_number IS NOT NULL THEN
    RETURN v_existing_order_number;
  END IF;

  BEGIN
    INSERT INTO public.orders (
      id, user_id, total, status, payment_method, payment_status, order_number,
      pickup_code, estimated_minutes, payment_reference, client_request_id
    ) VALUES (
      v_order_id, p_user_id, 0, p_status, p_payment_method, p_payment_status,
      v_order_number, p_pickup_code, p_estimated_minutes, p_payment_reference, p_request_id
    );
  EXCEPTION WHEN unique_violation THEN
    SELECT order_number INTO v_existing_order_number
    FROM public.orders
    WHERE client_request_id = p_request_id
      AND user_id = p_user_id;
    IF v_existing_order_number IS NOT NULL THEN
      RETURN v_existing_order_number;
    END IF;
    RAISE;
  END;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_quantity := COALESCE((v_item ->> 'quantity')::INTEGER, 0);
    IF v_quantity <= 0 THEN
      RAISE EXCEPTION 'invalid_quantity';
    END IF;

    SELECT * INTO v_product
    FROM public.products
    WHERE id = (v_item ->> 'product_id')::UUID
    FOR UPDATE;

    IF NOT FOUND OR v_product.available IS DISTINCT FROM true THEN
      RAISE EXCEPTION 'product_unavailable';
    END IF;
    IF v_product.stock < v_quantity THEN
      RAISE EXCEPTION 'insufficient_stock';
    END IF;

    UPDATE public.products
    SET stock = stock - v_quantity
    WHERE id = v_product.id;

    INSERT INTO public.order_items (order_id, product_id, quantity, price)
    VALUES (v_order_id, v_product.id, v_quantity, v_product.price);
    v_total := v_total + (v_product.price * v_quantity);
  END LOOP;

  UPDATE public.orders SET total = v_total WHERE id = v_order_id;
  RETURN v_order_number;
END;
$$;

REVOKE ALL ON FUNCTION public.create_order_tx(UUID, TEXT, TEXT, TEXT, TEXT, INTEGER, TEXT, JSONB, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_order_tx(UUID, TEXT, TEXT, TEXT, TEXT, INTEGER, TEXT, JSONB, UUID) TO authenticated;

-- Preserve the older client signature during a rolling frontend deployment.
CREATE OR REPLACE FUNCTION public.create_order_tx(
  p_user_id UUID,
  p_payment_method TEXT,
  p_payment_status TEXT,
  p_status TEXT,
  p_pickup_code TEXT,
  p_estimated_minutes INTEGER,
  p_payment_reference TEXT,
  p_items JSONB
)
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT public.create_order_tx(
    p_user_id, p_payment_method, p_payment_status, p_status, p_pickup_code,
    p_estimated_minutes, p_payment_reference, p_items, gen_random_uuid()
  );
$$;

REVOKE ALL ON FUNCTION public.create_order_tx(UUID, TEXT, TEXT, TEXT, TEXT, INTEGER, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_order_tx(UUID, TEXT, TEXT, TEXT, TEXT, INTEGER, TEXT, JSONB) TO authenticated;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['system_audit_logs', 'system_health_checks']
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = table_name
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', table_name);
    END IF;
  END LOOP;
END;
$$;
